export const columnDescriptions = {
  "site.id": "Unique identifier for the site",
  "site.website": "Website URL or domain name",
  "site.niche": "Main topic or industry of the site",
  "site.contentCategories": "Categories of content on the site",
  "site.siteClassification": "Classification type of the site",
  "site.priceCategory": "Pricing category of the site",
  "site.domainAuthority": "Domain authority score",
  "site.pageAuthority": "Page authority score",
  "site.linkAttribute": "Type of link attribute",
  "site.ahrefTraffic": "Traffic estimate from Ahrefs",
  "site.spamScore": "Spam score of the site",
  "site.domainRating": "Domain rating score",
  "site.socialMediaPosting": "Indicates if social media posting is available",
  "site.costPrice": "Base cost price of the site",
  "site.sellingPrice": "Selling price of the site",
  "site.discount": "Discount amount offered",
  "site.adultPrice": "Price for adult content",
  "site.casinoAdultPrice": "Price for casino and adult content",
  "site.cbdPrice": "Price for CBD content",
  "site.linkInsertionCost": "Cost for link insertion",
  "site.websiteRemark": "Remarks about the website",
  "site.webIP": "IP address of the website",
  "site.webCountry": "Country where website is hosted",
  "site.turnAroundTime": "Expected turnaround time",
  "site.semrushTraffic": "Traffic estimate from SEMrush",
  "site.semrushFirstCountryName": "Name of first country by traffic",
  "site.semrushSecondCountryName": "Name of second country by traffic",
  "site.semrushFirstCountryTraffic": "Traffic from first country",
  "site.semrushSecondCountryTraffic": "Traffic from second country",
  "site.semrushThirdCountryName": "Name of third country by traffic",
  "site.semrushThirdCountryTraffic": "Traffic from third country",
  "site.semrushFourthCountryName": "Name of fourth country by traffic",
  "site.semrushFourthCountryTraffic": "Traffic from fourth country",
  "site.semrushFifthCountryName": "Name of fifth country by traffic",
  "site.semrushFifthCountryTraffic": "Traffic from fifth country",
  "site.similarwebTraffic": "Traffic estimate from SimilarWeb",
  "site.domainAuthorityUpdateDate": "Date of Domain Authority update",
  "site.websiteType": "Type of website",
  "site.language": "Primary language of the site",
  "site.disclaimer": "Disclaimer text for the site",
  "site.anchorText": "Indicates if anchor text is used",
  "site.bannerImagePrice": "Price for banner image placement",
  "site.costPriceUpdateDate": "Date of last cost price update",
  "site.pureCategory": "Pure category classification",
  "site.availability": "Indicates site availability",
  "site.isIndexed": "Indicates if site is indexed",
  "site.websiteStatus": "Current status of the website",
  "site.websiteQuality": "Quality rating of the website",
  "site.numberOfLinks": "Number of links on the site",
  "site.semrushUpdateDate": "Date of last SEMrush update",
  "site.semrushOrganicTraffic": "Organic traffic from SEMrush",
  "site.semrushOrganicTrafficLastUpdated": "Last update date for organic traffic",
  "site.createdAt": "Creation date of site record",
  "site.updatedAt": "Last update date of site record",
  "site.vendorId": "Identifier of associated vendor",
  "site.pocId": "Identifier of point of contact",
  "vendor.id": "Unique identifier for the vendor",
  "vendor.name": "Name of the vendor",
  "vendor.phone": "Vendor's phone number",
  "vendor.email": "Vendor's email address",
  "vendor.pitchedFrom": "Source where vendor was pitched",
  "vendor.bankName": "Name of vendor's bank",
  "vendor.accountNumber": "Vendor's bank account number",
  "vendor.ifscCode": "IFSC code for vendor's bank",
  "vendor.paypalId": "Vendor's PayPal ID",
  "vendor.skypeId": "Vendor's Skype ID",
  "vendor.upiId": "Vendor's UPI ID",
  "vendor.category": "Category of the vendor",
  "vendor.createdAt": "Creation date of vendor record",
  "vendor.updatedAt": "Last update date of vendor record",
  "vendor.pocId": "Point of contact ID for vendor",
  "client.id": "Unique identifier for the client",
  "client.name": "Name of the client",
  "client.phone": "Client's phone number",
  "client.email": "Client's email address",
  "client.fbId": "Client's Facebook ID",
  "client.contactedFrom": "Source where client was contacted",
  "client.website": "Client's website URL",
  "client.source": "Source of the client",
  "client.clientClientName": "Name of client's client",
  "client.projects": "Projects associated with client",
  "client.createdAt": "Creation date of client record",
  "client.updatedAt": "Last update date of client record",
  "client.pocId": "Point of contact ID for client",
  "order.id": "Unique identifier for the order",
  "order.orderNumber" : "Order number",
  "order.orderDate": "Date when order was placed",
  "order.orderStatus": "Current status of the order",
  "order.vendorAssignedDate": "Date when vendor was assigned",
  "order.orderStatusUpdateDate": "Date of last order status update",
  "order.publishDate": "Date of publication",
  "order.publishURL": "URL where content was published",
  "order.orderRemark": "Remarks about the order",
  "order.mainRemark": "Main remarks for the order",
  "order.clientPaymentRemark": "Remarks about client payment",
  "order.clientContentCost": "Cost of content for client",
  "order.clientProposedAmount": "Amount proposed by client",
  "order.clientPaymentStatus": "Status of client payment",
  "order.clientReceivedAmount": "Amount received from client",
  "order.clientPaymentDate": "Date of client payment",
  "order.vendorInvoiceStatus": "Status of vendor invoice",
  "order.vendorPaymentStatus": "Status of vendor payment",
  "order.vendorPaymentDate": "Date of vendor payment",
  "order.vendorPaymentAmount": "Amount paid to vendor",
  "order.invoiceNumber": "Invoice number for the order",
  "order.costPriceWithGST": "Cost price including GST",
  "order.indexedScreenShotLink": "Link to indexed screenshot",
  "order.siteId": "Identifier of associated site",
  "order.salesPersonId": "Identifier of sales person",
  "order.clientId": "Identifier of associated client",
  "order.createdAt": "Creation date of order record",
  "order.updatedAt": "Last update date of order record",
  "order.orderCostPrice" : "Latest cost price of the Site at the time of order placement",
  "poc.name": "Name of the point of contact",
  "salesPerson.name": "Name of the sales person"
};