import { PrismaClient } from "@prisma/client";

const vendorsSeed = [
  {
    id: 1,
    name: "Nova Corp",
    phone: "9876543210",
    email: "contact@novacorp.com",
    pitchedFrom: "New York",
    bankName: "Chase Bank",
    accountNumber: "123456789012",
    ifscCode: "CHAS0001234",
    paypalId: "nova.paypal@example.com",
    skypeId: "nova_skype1",
    upiId: "nova@upi",
    pocId: 2,
  },
  {
    id: 2,
    name: "Pixel Solutions",
    phone: "9123456789",
    email: "info@pixelsolutions.com",
    pitchedFrom: "San Francisco",
    bankName: "Wells Fargo",
    accountNumber: "987654321098",
    ifscCode: "WFBI0005678",
    paypalId: "pixel.paypal@example.com",
    skypeId: "pixel_skype2",
    upiId: "pixel@upi",
    pocId: 2,
  },
  {
    id: 3,
    name: "Cloud Nine",
    phone: "9988776655",
    email: "hello@cloudnine.com",
    pitchedFrom: "Chicago",
    bankName: "Bank of America",
    accountNumber: "567890123456",
    ifscCode: "BOFA0004321",
    paypalId: "cloud.paypal@example.com",
    skypeId: "cloud_skype3",
    upiId: "cloud@upi",
    pocId: 2,
  },
  {
    id: 4,
    name: "TechNest",
    phone: "9001122334",
    email: "support@technest.com",
    pitchedFrom: "Austin",
    bankName: "Citibank",
    accountNumber: "345612789012",
    ifscCode: "CITI0006789",
    paypalId: "tech.paypal@example.com",
    skypeId: "tech_skype4",
    upiId: "tech@upi",
    pocId: 2,
  },
  {
    id: 5,
    name: "Quantum Leap",
    phone: "9556677889",
    email: "contact@quantumleap.com",
    pitchedFrom: "Boston",
    bankName: "PNC Bank",
    accountNumber: "789012345678",
    ifscCode: "PNCC0009876",
    paypalId: "quantum.paypal@example.com",
    skypeId: "quantum_skype5",
    upiId: "quantum@upi",
    pocId: 2,
  },
  {
    id: 6,
    name: "BrightEdge",
    phone: "9445566778",
    email: "info@brightedge.com",
    pitchedFrom: "Seattle",
    bankName: "TD Bank",
    accountNumber: "210987654321",
    ifscCode: "TDBK0001357",
    paypalId: "bright.paypal@example.com",
    skypeId: "bright_skype6",
    upiId: "bright@upi",
    pocId: 2,
  },
  {
    id: 7,
    name: "BlueWave",
    phone: "9334455667",
    email: "hello@bluewave.com",
    pitchedFrom: "Denver",
    bankName: "Capital One",
    accountNumber: "654321098765",
    ifscCode: "CAPO0002468",
    paypalId: "blue.paypal@example.com",
    skypeId: "blue_skype7",
    upiId: "blue@upi",
    pocId: 2,
  },
  {
    id: 8,
    name: "IronClad",
    phone: "9223344556",
    email: "support@ironclad.com",
    pitchedFrom: "Atlanta",
    bankName: "US Bank",
    accountNumber: "432109876543",
    ifscCode: "USBK0003698",
    paypalId: "iron.paypal@example.com",
    skypeId: "iron_skype8",
    upiId: "iron@upi",
    pocId: 2,
  },
  {
    id: 9,
    name: "Sunrise Ventures",
    phone: "9112233445",
    email: "contact@sunriseventures.com",
    pitchedFrom: "Miami",
    bankName: "Santander",
    accountNumber: "876543210987",
    ifscCode: "SANR0001479",
    paypalId: "sunrise.paypal@example.com",
    skypeId: "sunrise_skype9",
    upiId: "sunrise@upi",
    pocId: 2,
  },
  {
    id: 10,
    name: "NexusPoint",
    phone: "9001122334",
    email: "info@nexuspoint.com",
    pitchedFrom: "Portland",
    bankName: "Regions Bank",
    accountNumber: "109876543210",
    ifscCode: "REGB0002589",
    paypalId: "nexus.paypal@example.com",
    skypeId: "nexus_skype10",
    upiId: "nexus@upi",
    pocId: 2,
  },
  {
    id: 11,
    name: "Vertex Labs",
    phone: "9898989898",
    email: "contact@vertexlabs.com",
    pitchedFrom: "Dallas",
    bankName: "HSBC",
    accountNumber: "102938475610",
    ifscCode: "HSBC0001234",
    paypalId: "vertex.paypal@example.com",
    skypeId: "vertex_skype11",
    upiId: "vertex@upi",
    pocId: 2,
  },
  {
    id: 12,
    name: "Apex Innovations",
    phone: "9765432198",
    email: "info@apexinnovations.com",
    pitchedFrom: "San Diego",
    bankName: "Barclays",
    accountNumber: "564738291056",
    ifscCode: "BARC0005678",
    paypalId: "apex.paypal@example.com",
    skypeId: "apex_skype12",
    upiId: "apex@upi",
    pocId: 2,
  },
  {
    id: 13,
    name: "Synergy Corp",
    phone: "9654321876",
    email: "hello@synergycorp.com",
    pitchedFrom: "Phoenix",
    bankName: "Deutsche Bank",
    accountNumber: "847362514709",
    ifscCode: "DEUT0004321",
    paypalId: "synergy.paypal@example.com",
    skypeId: "synergy_skype13",
    upiId: "synergy@upi",
    pocId: 2,
  },
  {
    id: 14,
    name: "Infinity Solutions",
    phone: "9543218765",
    email: "support@infinitysolutions.com",
    pitchedFrom: "Philadelphia",
    bankName: "Credit Suisse",
    accountNumber: "374829105647",
    ifscCode: "CSFB0006789",
    paypalId: "infinity.paypal@example.com",
    skypeId: "infinity_skype14",
    upiId: "infinity@upi",
    pocId: 2,
  },
  {
    id: 15,
    name: "Pinnacle Tech",
    phone: "9432187654",
    email: "contact@pinnacletech.com",
    pitchedFrom: "Houston",
    bankName: "UBS",
    accountNumber: "293847561029",
    ifscCode: "UBSN0009876",
    paypalId: "pinnacle.paypal@example.com",
    skypeId: "pinnacle_skype15",
    upiId: "pinnacle@upi",
    pocId: 2,
  },
  {
    id: 16,
    name: "Summit Enterprises",
    phone: "9321876543",
    email: "info@summitenterprises.com",
    pitchedFrom: "Columbus",
    bankName: "Royal Bank",
    accountNumber: "019283746501",
    ifscCode: "RYBK0001357",
    paypalId: "summit.paypal@example.com",
    skypeId: "summit_skype16",
    upiId: "summit@upi",
    pocId: 2,
  },
  {
    id: 17,
    name: "Elevate Corp",
    phone: "9218765432",
    email: "hello@elevatecorp.com",
    pitchedFrom: "Charlotte",
    bankName: "Santander UK",
    accountNumber: "564738291065",
    ifscCode: "SANR0002468",
    paypalId: "elevate.paypal@example.com",
    skypeId: "elevate_skype17",
    upiId: "elevate@upi",
    pocId: 2,
  },
  {
    id: 18,
    name: "Zenith Solutions",
    phone: "9109876543",
    email: "support@zenithsolutions.com",
    pitchedFrom: "Indianapolis",
    bankName: "Standard Chartered",
    accountNumber: "837465920173",
    ifscCode: "SCBL0003698",
    paypalId: "zenith.paypal@example.com",
    skypeId: "zenith_skype18",
    upiId: "zenith@upi",
    pocId: 2,
  },
  {
    id: 19,
    name: "Vortex Technologies",
    phone: "9098765432",
    email: "contact@vortextech.com",
    pitchedFrom: "San Jose",
    bankName: "BNP Paribas",
    accountNumber: "746291038475",
    ifscCode: "BNPA0001479",
    paypalId: "vortex.paypal@example.com",
    skypeId: "vortex_skype19",
    upiId: "vortex@upi",
    pocId: 2,
  },
  {
    id: 20,
    name: "Pioneer Systems",
    phone: "9087654321",
    email: "info@pioneersystems.com",
    pitchedFrom: "Fort Worth",
    bankName: "ING Bank",
    accountNumber: "928374650192",
    ifscCode: "INGB0002589",
    paypalId: "pioneer.paypal@example.com",
    skypeId: "pioneer_skype20",
    upiId: "pioneer@upi",
    pocId: 2,
  },
  {
    id: 21,
    name: "Crest Innovations",
    phone: "9076543210",
    email: "hello@crestinnovations.com",
    pitchedFrom: "Detroit",
    bankName: "Rabobank",
    accountNumber: "109283746592",
    ifscCode: "RABO0003698",
    paypalId: "crest.paypal@example.com",
    skypeId: "crest_skype21",
    upiId: "crest@upi",
    pocId: 2,
  },
  {
    id: 22,
    name: "Vertex Dynamics",
    phone: "9065432109",
    email: "support@vertexdynamics.com",
    pitchedFrom: "Memphis",
    bankName: "Mizuho Bank",
    accountNumber: "564738291027",
    ifscCode: "MIZU0001479",
    paypalId: "vertexd.paypal@example.com",
    skypeId: "vertexd_skype22",
    upiId: "vertexd@upi",
    pocId: 2,
  },
  {
    id: 23,
    name: "Summit Peak",
    phone: "9054321098",
    email: "contact@summitpeak.com",
    pitchedFrom: "Baltimore",
    bankName: "Banco Santander",
    accountNumber: "837465920184",
    ifscCode: "BSAN0002589",
    paypalId: "summitp.paypal@example.com",
    skypeId: "summitp_skype23",
    upiId: "summitp@upi",
    pocId: 2,
  },
  {
    id: 24,
    name: "Optima Tech",
    phone: "9043210987",
    email: "info@optimatech.com",
    pitchedFrom: "Boston",
    bankName: "Nordea Bank",
    accountNumber: "746291038476",
    ifscCode: "NDEA0003698",
    paypalId: "optima.paypal@example.com",
    skypeId: "optima_skype24",
    upiId: "optima@upi",
    pocId: 2,
  },
  {
    id: 25,
    name: "Everest Solutions",
    phone: "9032109876",
    email: "hello@everestsolutions.com",
    pitchedFrom: "Seattle",
    bankName: "Credit Agricole",
    accountNumber: "928374650193",
    ifscCode: "CRAG0001479",
    paypalId: "everest.paypal@example.com",
    skypeId: "everest_skype25",
    upiId: "everest@upi",
    pocId: 2,
  },
  {
    id: 26,
    name: "SummitWave",
    phone: "9021098765",
    email: "support@summitwave.com",
    pitchedFrom: "Denver",
    bankName: "Bank of Montreal",
    accountNumber: "109283746593",
    ifscCode: "BMOF0002589",
    paypalId: "summitw.paypal@example.com",
    skypeId: "summitw_skype26",
    upiId: "summitw@upi",
    pocId: 2,
  },
  {
    id: 27,
    name: "Ignite Corp",
    phone: "9010987654",
    email: "contact@ignitecorp.com",
    pitchedFrom: "Miami",
    bankName: "Commonwealth Bank",
    accountNumber: "564738291028",
    ifscCode: "CBAU0003698",
    paypalId: "ignite.paypal@example.com",
    skypeId: "ignite_skype27",
    upiId: "ignite@upi",
    pocId: 2,
  },
  {
    id: 28,
    name: "BluePeak",
    phone: "9009876543",
    email: "info@bluepeak.com",
    pitchedFrom: "Portland",
    bankName: "Rabobank",
    accountNumber: "837465920185",
    ifscCode: "RABO0001479",
    paypalId: "bluepeak.paypal@example.com",
    skypeId: "bluepeak_skype28",
    upiId: "bluepeak@upi",
    pocId: 2,
  },
  {
    id: 29,
    name: "PrimeWave",
    phone: "8998765432",
    email: "hello@primewave.com",
    pitchedFrom: "Dallas",
    bankName: "KBC Bank",
    accountNumber: "746291038477",
    ifscCode: "KBCB0003698",
    paypalId: "primewave.paypal@example.com",
    skypeId: "primewave_skype29",
    upiId: "primewave@upi",
    pocId: 2,
  },
  {
    id: 30,
    name: "Skyline Dynamics",
    phone: "8987654321",
    email: "support@skylinedynamics.com",
    pitchedFrom: "San Diego",
    bankName: "ABN AMRO",
    accountNumber: "928374650194",
    ifscCode: "ABNA0001479",
    paypalId: "skyline.paypal@example.com",
    skypeId: "skyline_skype30",
    upiId: "skyline@upi",
    pocId: 2,
  },
  {
    id: 31,
    name: "AeroTech",
    phone: "8976543210",
    email: "contact@aerotech.com",
    pitchedFrom: "Phoenix",
    bankName: "DZ Bank",
    accountNumber: "109283746594",
    ifscCode: "DZBK0002589",
    paypalId: "aerotech.paypal@example.com",
    skypeId: "aerotech_skype31",
    upiId: "aerotech@upi",
    pocId: 2,
  },
  {
    id: 32,
    name: "Optimum Solutions",
    phone: "8965432109",
    email: "info@optimumsolutions.com",
    pitchedFrom: "Philadelphia",
    bankName: "KBC Bank",
    accountNumber: "564738291029",
    ifscCode: "KBCB0003698",
    paypalId: "optimum.paypal@example.com",
    skypeId: "optimum_skype32",
    upiId: "optimum@upi",
    pocId: 2,
  },
  {
    id: 33,
    name: "CrestPoint",
    phone: "8954321098",
    email: "hello@crestpoint.com",
    pitchedFrom: "Houston",
    bankName: "Handelsbanken",
    accountNumber: "837465920186",
    ifscCode: "HAND0001479",
    paypalId: "crestpoint.paypal@example.com",
    skypeId: "crestpoint_skype33",
    upiId: "crestpoint@upi",
    pocId: 2,
  },
  {
    id: 34,
    name: "SynergyWave",
    phone: "8943210987",
    email: "support@synergywave.com",
    pitchedFrom: "Columbus",
    bankName: "Credit Suisse",
    accountNumber: "746291038478",
    ifscCode: "CSFB0003698",
    paypalId: "synergywave.paypal@example.com",
    skypeId: "synergywave_skype34",
    upiId: "synergywave@upi",
    pocId: 2,
  },
  {
    id: 35,
    name: "Blue Horizon",
    phone: "8932109876",
    email: "contact@bluehorizon.com",
    pitchedFrom: "Charlotte",
    bankName: "Danske Bank",
    accountNumber: "928374650195",
    ifscCode: "DANS0001479",
    paypalId: "bluehorizon.paypal@example.com",
    skypeId: "bluehorizon_skype35",
    upiId: "bluehorizon@upi",
    pocId: 2,
  },
  {
    id: 36,
    name: "Prime Solutions",
    phone: "8921098765",
    email: "info@primesolutions.com",
    pitchedFrom: "Indianapolis",
    bankName: "UniCredit",
    accountNumber: "109283746595",
    ifscCode: "UNCR0002589",
    paypalId: "prime.paypal@example.com",
    skypeId: "prime_skype36",
    upiId: "prime@upi",
    pocId: 2,
  },
  {
    id: 37,
    name: "Summit Tech",
    phone: "8910987654",
    email: "hello@summittech.com",
    pitchedFrom: "San Jose",
    bankName: "Raiffeisen Bank",
    accountNumber: "564738291030",
    ifscCode: "RAIF0003698",
    paypalId: "summittech.paypal@example.com",
    skypeId: "summittech_skype37",
    upiId: "summittech@upi",
    pocId: 2,
  },
  {
    id: 38,
    name: "Elevate Dynamics",
    phone: "8909876543",
    email: "support@elevatedynamics.com",
    pitchedFrom: "Fort Worth",
    bankName: "Intesa Sanpaolo",
    accountNumber: "837465920187",
    ifscCode: "INTS0001479",
    paypalId: "elevatedynamics.paypal@example.com",
    skypeId: "elevatedynamics_skype38",
    upiId: "elevatedynamics@upi",
    pocId: 2,
  },
  {
    id: 39,
    name: "Quantum Systems",
    phone: "8898765432",
    email: "contact@quantumsystems.com",
    pitchedFrom: "Detroit",
    bankName: "Banco do Brasil",
    accountNumber: "746291038479",
    ifscCode: "BBAS0003698",
    paypalId: "quantumsystems.paypal@example.com",
    skypeId: "quantumsystems_skype39",
    upiId: "quantumsystems@upi",
    pocId: 2,
  },
  {
    id: 40,
    name: "Skyline Innovations",
    phone: "8887654321",
    email: "info@skylineinnovations.com",
    pitchedFrom: "Memphis",
    bankName: "Banque Populaire",
    accountNumber: "928374650196",
    ifscCode: "BPOP0001479",
    paypalId: "skylineinnovations.paypal@example.com",
    skypeId: "skylineinnovations_skype40",
    upiId: "skylineinnovations@upi",
    pocId: 2,
  },
  {
    id: 41,
    name: "Ignite Dynamics",
    phone: "8876543210",
    email: "hello@ignitedynamics.com",
    pitchedFrom: "Baltimore",
    bankName: "Bankia",
    accountNumber: "109283746596",
    ifscCode: "BANK0002589",
    paypalId: "ignitedynamics.paypal@example.com",
    skypeId: "ignitedynamics_skype41",
    upiId: "ignitedynamics@upi",
    pocId: 2,
  },
  {
    id: 42,
    name: "BluePeak Tech",
    phone: "8865432109",
    email: "support@bluepeaktech.com",
    pitchedFrom: "Boston",
    bankName: "Rabobank",
    accountNumber: "564738291031",
    ifscCode: "RABO0003698",
    paypalId: "bluepeaktech.paypal@example.com",
    skypeId: "bluepeaktech_skype42",
    upiId: "bluepeaktech@upi",
    pocId: 2,
  },
  {
    id: 43,
    name: "PrimeWave Solutions",
    phone: "8854321098",
    email: "contact@primewavesolutions.com",
    pitchedFrom: "Houston",
    bankName: "Handelsbanken",
    accountNumber: "837465920188",
    ifscCode: "HAND0001479",
    paypalId: "primewavesolutions.paypal@example.com",
    skypeId: "primewavesolutions_skype43",
    upiId: "primewavesolutions@upi",
    pocId: 2,
  },
  {
    id: 44,
    name: "Skyline Dynamics Corp",
    phone: "8843210987",
    email: "info@skylinedynamicscorp.com",
    pitchedFrom: "Columbus",
    bankName: "Credit Suisse",
    accountNumber: "746291038480",
    ifscCode: "CSFB0003698",
    paypalId: "skylinedynamicscorp.paypal@example.com",
    skypeId: "skylinedynamicscorp_skype44",
    upiId: "skylinedynamicscorp@upi",
    pocId: 2,
  },
  {
    id: 45,
    name: "AeroTech Solutions",
    phone: "8832109876",
    email: "hello@aerotechsolutions.com",
    pitchedFrom: "Charlotte",
    bankName: "Danske Bank",
    accountNumber: "928374650197",
    ifscCode: "DANS0001479",
    paypalId: "aerotechsolutions.paypal@example.com",
    skypeId: "aerotechsolutions_skype45",
    upiId: "aerotechsolutions@upi",
    pocId: 2,
  },
  {
    id: 46,
    name: "Optimum Systems",
    phone: "8821098765",
    email: "support@optimumsystems.com",
    pitchedFrom: "Indianapolis",
    bankName: "UniCredit",
    accountNumber: "109283746597",
    ifscCode: "UNCR0002589",
    paypalId: "optimumsystems.paypal@example.com",
    skypeId: "optimumsystems_skype46",
    upiId: "optimumsystems@upi",
    pocId: 2,
  },
  {
    id: 47,
    name: "CrestPoint Dynamics",
    phone: "8810987654",
    email: "contact@crestpointdynamics.com",
    pitchedFrom: "San Jose",
    bankName: "Raiffeisen Bank",
    accountNumber: "564738291032",
    ifscCode: "RAIF0003698",
    paypalId: "crestpointdynamics.paypal@example.com",
    skypeId: "crestpointdynamics_skype47",
    upiId: "crestpointdynamics@upi",
    pocId: 2,
  },
  {
    id: 48,
    name: "SynergyWave Corp",
    phone: "8809876543",
    email: "info@synergywavecorp.com",
    pitchedFrom: "Fort Worth",
    bankName: "Intesa Sanpaolo",
    accountNumber: "837465920189",
    ifscCode: "INTS0001479",
    paypalId: "synergywavecorp.paypal@example.com",
    skypeId: "synergywavecorp_skype48",
    upiId: "synergywavecorp@upi",
    pocId: 2,
  },
  {
    id: 49,
    name: "Blue Horizon Systems",
    phone: "8798765432",
    email: "hello@bluehorizonsystems.com",
    pitchedFrom: "Detroit",
    bankName: "Banco do Brasil",
    accountNumber: "746291038481",
    ifscCode: "BBAS0003698",
    paypalId: "bluehorizonsystems.paypal@example.com",
    skypeId: "bluehorizonsystems_skype49",
    upiId: "bluehorizonsystems@upi",
    pocId: 2,
  },
  {
    id: 50,
    name: "Prime Innovations",
    phone: "8787654321",
    email: "support@primeinnovations.com",
    pitchedFrom: "Memphis",
    bankName: "Banque Populaire",
    accountNumber: "928374650198",
    ifscCode: "BPOP0001479",
    paypalId: "primeinnovations.paypal@example.com",
    skypeId: "primeinnovations_skype50",
    upiId: "primeinnovations@upi",
    pocId: 2,
  },
];


const prisma = new PrismaClient();
async function main() {
  console.log("Seeding vendors...");
  for (const vendor of vendorsSeed) {
    await prisma.vendor.create({
      data: vendor,
    });
  }
  console.log("Vendors seeded successfully.");
}

main(); 