import { PrismaClient } from '@prisma/client';

const seedClient = [
  {
    id: 1,
    name: "Apex Solutions",
    phone: "+1-202-555-0111",
    email: "contact@apexsolutions.com",
    fbId: "apex.solutions.fb",
    contactedFrom: "LinkedIn",
    website: "https://www.apexsolutions.com",
    source: "Referral",
    clientClientName: "John Doe",
    companyName: "Apex Solutions LLC",
    projects: "Website Development, SEO",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 2,
    name: "Blue Ocean Enterprises",
    phone: "+1-202-555-0122",
    email: "info@blueocean.com",
    fbId: "blueocean.fb",
    contactedFrom: "Website",
    website: "https://www.blueocean.com",
    source: "Cold Email",
    clientClientName: "Jane Smith",
    companyName: "Blue Ocean Enterprises Inc.",
    projects: "Mobile App, Branding",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 3,
    name: "Crestview Group",
    phone: "+44-20-7946-0958",
    email: "hello@crestview.co.uk",
    fbId: "crestview.group.fb",
    contactedFrom: "Conference",
    website: "https://www.crestview.co.uk",
    source: "Event",
    clientClientName: "Robert Brown",
    companyName: "Crestview Group Ltd.",
    projects: "Digital Marketing, PPC",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 4,
    name: "Delta Technologies",
    phone: "+91-98765-43210",
    email: "contact@deltatech.in",
    fbId: "delta.tech.fb",
    contactedFrom: "Referral",
    website: "https://www.deltatech.in",
    source: "Partner",
    clientClientName: "Priya Singh",
    companyName: "Delta Technologies Pvt Ltd",
    projects: "Cloud Migration, DevOps",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 5,
    name: "Echo Innovations",
    phone: "+1-310-555-0199",
    email: "support@echoinnovations.com",
    fbId: "echo.innovations.fb",
    contactedFrom: "LinkedIn",
    website: "https://www.echoinnovations.com",
    source: "Online Ad",
    clientClientName: "Alice Johnson",
    companyName: "Echo Innovations LLC",
    projects: "UX/UI Design, Website Revamp",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 6,
    name: "Falcon Dynamics",
    phone: "+61-2-5550-1234",
    email: "contact@falcondynamics.au",
    fbId: "falcon.dynamics.fb",
    contactedFrom: "Cold Call",
    website: "https://www.falcondynamics.au",
    source: "Cold Call",
    clientClientName: "Michael Green",
    companyName: "Falcon Dynamics Pty Ltd",
    projects: "ERP Implementation",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 7,
    name: "Gamma Enterprises",
    phone: "+49-30-1234567",
    email: "info@gamma-enterprises.de",
    fbId: "gamma.enterprises.fb",
    contactedFrom: "Email Campaign",
    website: "https://www.gamma-enterprises.de",
    source: "Email",
    clientClientName: "Anna Müller",
    companyName: "Gamma Enterprises GmbH",
    projects: "Data Analytics",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 8,
    name: "Horizon Ventures",
    phone: "+1-415-555-0123",
    email: "contact@horizonventures.com",
    fbId: "horizon.ventures.fb",
    contactedFrom: "Referral",
    website: "https://www.horizonventures.com",
    source: "Referral",
    clientClientName: "David Lee",
    companyName: "Horizon Ventures Inc.",
    projects: "Mobile Development",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 9,
    name: "Ironclad Solutions",
    phone: "+44-161-555-0145",
    email: "support@ironcladsolutions.co.uk",
    fbId: "ironclad.solutions.fb",
    contactedFrom: "Website",
    website: "https://www.ironcladsolutions.co.uk",
    source: "Website",
    clientClientName: "Emma Wilson",
    companyName: "Ironclad Solutions Ltd.",
    projects: "Cybersecurity",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 10,
    name: "Jupiter Consulting",
    phone: "+91-9988776655",
    email: "info@jupiterconsulting.in",
    fbId: "jupiter.consulting.fb",
    contactedFrom: "Conference",
    website: "https://www.jupiterconsulting.in",
    source: "Event",
    clientClientName: "Rahul Sharma",
    companyName: "Jupiter Consulting Pvt Ltd",
    projects: "Business Analysis",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 11,
    name: "Krypton Labs",
    phone: "+1-212-555-0177",
    email: "contact@kryptonlabs.com",
    fbId: "krypton.labs.fb",
    contactedFrom: "LinkedIn",
    website: "https://www.kryptonlabs.com",
    source: "Referral",
    clientClientName: "Sophia Martinez",
    companyName: "Krypton Labs LLC",
    projects: "AI Research",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 12,
    name: "Lunar Tech",
    phone: "+1-650-555-0118",
    email: "hello@lunartech.com",
    fbId: "lunar.tech.fb",
    contactedFrom: "Cold Email",
    website: "https://www.lunartech.com",
    source: "Cold Email",
    clientClientName: "Brian Adams",
    companyName: "Lunar Tech Inc.",
    projects: "Cloud Services",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 13,
    name: "Maverick Solutions",
    phone: "+44-20-7946-0711",
    email: "info@mavericksolutions.co.uk",
    fbId: "maverick.solutions.fb",
    contactedFrom: "Referral",
    website: "https://www.mavericksolutions.co.uk",
    source: "Referral",
    clientClientName: "Olivia King",
    companyName: "Maverick Solutions Ltd.",
    projects: "Blockchain",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 14,
    name: "Nexus Innovations",
    phone: "+91-9123456789",
    email: "contact@nexusinnovations.in",
    fbId: "nexus.innovations.fb",
    contactedFrom: "Event",
    website: "https://www.nexusinnovations.in",
    source: "Conference",
    clientClientName: "Amit Patel",
    companyName: "Nexus Innovations Pvt Ltd",
    projects: "IoT Development",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 15,
    name: "Orion Ventures",
    phone: "+1-718-555-0144",
    email: "info@orionventures.com",
    fbId: "orion.ventures.fb",
    contactedFrom: "Website",
    website: "https://www.orionventures.com",
    source: "Website",
    clientClientName: "Jessica Nguyen",
    companyName: "Orion Ventures LLC",
    projects: "Software Development",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 16,
    name: "Pinnacle Partners",
    phone: "+44-161-555-0199",
    email: "contact@pinnaclepartners.co.uk",
    fbId: "pinnacle.partners.fb",
    contactedFrom: "LinkedIn",
    website: "https://www.pinnaclepartners.co.uk",
    source: "LinkedIn",
    clientClientName: "Liam Johnson",
    companyName: "Pinnacle Partners Ltd.",
    projects: "Data Science",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 17,
    name: "Quantum Solutions",
    phone: "+1-415-555-0133",
    email: "hello@quantumsolutions.com",
    fbId: "quantum.solutions.fb",
    contactedFrom: "Cold Call",
    website: "https://www.quantumsolutions.com",
    source: "Cold Call",
    clientClientName: "Isabella Lopez",
    companyName: "Quantum Solutions Inc.",
    projects: "Cybersecurity",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 18,
    name: "Radiant Enterprises",
    phone: "+91-9988776654",
    email: "info@radiantenterprises.in",
    fbId: "radiant.enterprises.fb",
    contactedFrom: "Referral",
    website: "https://www.radiantenterprises.in",
    source: "Referral",
    clientClientName: "Sanjay Kumar",
    companyName: "Radiant Enterprises Pvt Ltd",
    projects: "ERP Systems",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 19,
    name: "Summit Technologies",
    phone: "+1-212-555-0167",
    email: "contact@summittechnologies.com",
    fbId: "summit.technologies.fb",
    contactedFrom: "Email Campaign",
    website: "https://www.summittechnologies.com",
    source: "Email",
    clientClientName: "Mia Davis",
    companyName: "Summit Technologies LLC",
    projects: "Mobile Apps",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
    id: 20,
    name: "Titan Solutions",
    phone: "+44-20-7946-0999",
    email: "info@titansolutions.co.uk",
    fbId: "titan.solutions.fb",
    contactedFrom: "Website",
    website: "https://www.titansolutions.co.uk",
    source: "Website",
    clientClientName: "Oliver Wilson",
    companyName: "Titan Solutions Ltd.",
    projects: "Cloud Computing",
    createdAt: new Date(),
    updatedAt: new Date(),
    pocId: 2,
  },
  {
  id: 21,
  name: "UltraTech Dynamics",
  phone: "+1-303-555-0188",
  email: "contact@ultratechdynamics.com",
  fbId: "ultratech.dynamics.fb",
  contactedFrom: "LinkedIn",
  website: "https://www.ultratechdynamics.com",
  source: "Referral",
  clientClientName: "Ella Thompson",
  companyName: "UltraTech Dynamics LLC",
  projects: "AI and Machine Learning",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 22,
  name: "Velocity Corp",
  phone: "+44-161-555-0200",
  email: "info@velocitycorp.co.uk",
  fbId: "velocity.corp.fb",
  contactedFrom: "Website",
  website: "https://www.velocitycorp.co.uk",
  source: "Website",
  clientClientName: "Jack Harris",
  companyName: "Velocity Corporation Ltd.",
  projects: "Big Data Analytics",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 23,
  name: "Westbridge Solutions",
  phone: "+91-9876543210",
  email: "support@westbridge.in",
  fbId: "westbridge.solutions.fb",
  contactedFrom: "Conference",
  website: "https://www.westbridge.in",
  source: "Event",
  clientClientName: "Nisha Verma",
  companyName: "Westbridge Solutions Pvt Ltd",
  projects: "ERP Implementation",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 24,
  name: "Xenon Tech",
  phone: "+1-408-555-0172",
  email: "hello@xenontech.com",
  fbId: "xenon.tech.fb",
  contactedFrom: "Cold Email",
  website: "https://www.xenontech.com",
  source: "Cold Email",
  clientClientName: "Ryan Scott",
  companyName: "Xenon Tech Inc.",
  projects: "Cloud Infrastructure",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 25,
  name: "Yellowstone Industries",
  phone: "+44-20-7946-0899",
  email: "info@yellowstone.co.uk",
  fbId: "yellowstone.industries.fb",
  contactedFrom: "Referral",
  website: "https://www.yellowstone.co.uk",
  source: "Referral",
  clientClientName: "Sophie Carter",
  companyName: "Yellowstone Industries Ltd.",
  projects: "Mobile Development",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 26,
  name: "Zenith Partners",
  phone: "+1-212-555-0184",
  email: "contact@zenithpartners.com",
  fbId: "zenith.partners.fb",
  contactedFrom: "Website",
  website: "https://www.zenithpartners.com",
  source: "Website",
  clientClientName: "Mark Evans",
  companyName: "Zenith Partners LLC",
  projects: "Blockchain Integration",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 27,
  name: "Atlas Innovations",
  phone: "+91-9999888777",
  email: "info@atlasinnovations.in",
  fbId: "atlas.innovations.fb",
  contactedFrom: "Event",
  website: "https://www.atlasinnovations.in",
  source: "Conference",
  clientClientName: "Rohit Sharma",
  companyName: "Atlas Innovations Pvt Ltd",
  projects: "IoT Solutions",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 28,
  name: "Brightside Media",
  phone: "+1-650-555-0166",
  email: "support@brightsidemedia.com",
  fbId: "brightside.media.fb",
  contactedFrom: "LinkedIn",
  website: "https://www.brightsidemedia.com",
  source: "Referral",
  clientClientName: "Laura Mitchell",
  companyName: "Brightside Media LLC",
  projects: "Digital Marketing",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 29,
  name: "Catalyst Solutions",
  phone: "+44-161-555-0212",
  email: "info@catalystsolutions.co.uk",
  fbId: "catalyst.solutions.fb",
  contactedFrom: "Email Campaign",
  website: "https://www.catalystsolutions.co.uk",
  source: "Email",
  clientClientName: "Ethan Wright",
  companyName: "Catalyst Solutions Ltd.",
  projects: "Cybersecurity",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 30,
  name: "DeltaWave Tech",
  phone: "+1-303-555-0199",
  email: "contact@deltawavetech.com",
  fbId: "deltawave.tech.fb",
  contactedFrom: "Cold Call",
  website: "https://www.deltawavetech.com",
  source: "Cold Call",
  clientClientName: "Michelle Rivera",
  companyName: "DeltaWave Tech Inc.",
  projects: "AI & ML",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 31,
  name: "Echelon Enterprises",
  phone: "+91-9123456780",
  email: "info@echelonenterprises.in",
  fbId: "echelon.enterprises.fb",
  contactedFrom: "Referral",
  website: "https://www.echelonenterprises.in",
  source: "Referral",
  clientClientName: "Anjali Gupta",
  companyName: "Echelon Enterprises Pvt Ltd",
  projects: "ERP Solutions",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 32,
  name: "FalconTech Solutions",
  phone: "+1-415-555-0190",
  email: "support@falcontechsolutions.com",
  fbId: "falcontech.solutions.fb",
  contactedFrom: "Website",
  website: "https://www.falcontechsolutions.com",
  source: "Website",
  clientClientName: "Nathan Collins",
  companyName: "FalconTech Solutions LLC",
  projects: "Cloud Migration",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 33,
  name: "Gemini Innovations",
  phone: "+44-20-7946-0755",
  email: "contact@geminiinnovations.co.uk",
  fbId: "gemini.innovations.fb",
  contactedFrom: "Event",
  website: "https://www.geminiinnovations.co.uk",
  source: "Conference",
  clientClientName: "Sarah Johnson",
  companyName: "Gemini Innovations Ltd.",
  projects: "Mobile Apps",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 34,
  name: "Helix Ventures",
  phone: "+1-212-555-0183",
  email: "info@helixventures.com",
  fbId: "helix.ventures.fb",
  contactedFrom: "LinkedIn",
  website: "https://www.helixventures.com",
  source: "LinkedIn",
  clientClientName: "Jason Clark",
  companyName: "Helix Ventures LLC",
  projects: "Data Analytics",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 35,
  name: "Ignite Labs",
  phone: "+91-9988776651",
  email: "hello@ignitelabs.in",
  fbId: "ignite.labs.fb",
  contactedFrom: "Cold Email",
  website: "https://www.ignitelabs.in",
  source: "Cold Email",
  clientClientName: "Kiran Rao",
  companyName: "Ignite Labs Pvt Ltd",
  projects: "IoT Projects",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 36,
  name: "Juno Technologies",
  phone: "+1-650-555-0170",
  email: "contact@junotechnologies.com",
  fbId: "juno.technologies.fb",
  contactedFrom: "Website",
  website: "https://www.junotechnologies.com",
  source: "Website",
  clientClientName: "Megan Stewart",
  companyName: "Juno Technologies Inc.",
  projects: "Software Development",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 37,
  name: "Keystone Solutions",
  phone: "+44-161-555-0220",
  email: "info@keystonesolutions.co.uk",
  fbId: "keystone.solutions.fb",
  contactedFrom: "Referral",
  website: "https://www.keystonesolutions.co.uk",
  source: "Referral",
  clientClientName: "Lara Bennett",
  companyName: "Keystone Solutions Ltd.",
  projects: "Blockchain",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 38,
  name: "Lumos Tech",
  phone: "+1-310-555-0182",
  email: "support@lumostech.com",
  fbId: "lumos.tech.fb",
  contactedFrom: "Email Campaign",
  website: "https://www.lumostech.com",
  source: "Email",
  clientClientName: "Derek Harris",
  companyName: "Lumos Tech LLC",
  projects: "Cloud Services",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 39,
  name: "Meridian Enterprises",
  phone: "+91-9876543212",
  email: "contact@meridianenterprises.in",
  fbId: "meridian.enterprises.fb",
  contactedFrom: "Cold Call",
  website: "https://www.meridianenterprises.in",
  source: "Cold Call",
  clientClientName: "Ritu Sharma",
  companyName: "Meridian Enterprises Pvt Ltd",
  projects: "Cybersecurity",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 40,
  name: "Nimbus Technologies",
  phone: "+1-212-555-0155",
  email: "info@nimbustechnologies.com",
  fbId: "nimbus.technologies.fb",
  contactedFrom: "Website",
  website: "https://www.nimbustechnologies.com",
  source: "Website",
  clientClientName: "Grace Williams",
  companyName: "Nimbus Technologies LLC",
  projects: "Mobile Development",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 41,
  name: "Onyx Solutions",
  phone: "+44-20-7946-0811",
  email: "contact@onyxsolutions.co.uk",
  fbId: "onyx.solutions.fb",
  contactedFrom: "Referral",
  website: "https://www.onyxsolutions.co.uk",
  source: "Referral",
  clientClientName: "Harry Clarke",
  companyName: "Onyx Solutions Ltd.",
  projects: "ERP Systems",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 42,
  name: "Pinnacle Tech",
  phone: "+91-9988776611",
  email: "support@pinnacletech.in",
  fbId: "pinnacle.tech.fb",
  contactedFrom: "LinkedIn",
  website: "https://www.pinnacletech.in",
  source: "LinkedIn",
  clientClientName: "Sunil Kumar",
  companyName: "Pinnacle Tech Pvt Ltd",
  projects: "AI and Automation",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 43,
  name: "Quantum Dynamics",
  phone: "+1-650-555-0161",
  email: "info@quantumdynamics.com",
  fbId: "quantum.dynamics.fb",
  contactedFrom: "Cold Email",
  website: "https://www.quantumdynamics.com",
  source: "Cold Email",
  clientClientName: "Isabella Morris",
  companyName: "Quantum Dynamics LLC",
  projects: "Big Data",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 44,
  name: "Radian Enterprises",
  phone: "+44-161-555-0230",
  email: "contact@radianenterprises.co.uk",
  fbId: "radian.enterprises.fb",
  contactedFrom: "Event",
  website: "https://www.radianenterprises.co.uk",
  source: "Conference",
  clientClientName: "Sophia Turner",
  companyName: "Radian Enterprises Ltd.",
  projects: "Digital Marketing",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 45,
  name: "Sierra Solutions",
  phone: "+1-212-555-0142",
  email: "hello@sierrasolutions.com",
  fbId: "sierra.solutions.fb",
  contactedFrom: "Website",
  website: "https://www.sierrasolutions.com",
  source: "Website",
  clientClientName: "Ethan Hall",
  companyName: "Sierra Solutions LLC",
  projects: "Cloud Computing",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 46,
  name: "Titan Technologies",
  phone: "+91-9876543299",
  email: "info@titantechnologies.in",
  fbId: "titan.technologies.fb",
  contactedFrom: "Referral",
  website: "https://www.titantechnologies.in",
  source: "Referral",
  clientClientName: "Anita Das",
  companyName: "Titan Technologies Pvt Ltd",
  projects: "Blockchain",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 47,
  name: "Uplift Ventures",
  phone: "+1-303-555-0158",
  email: "contact@upliftventures.com",
  fbId: "uplift.ventures.fb",
  contactedFrom: "Cold Call",
  website: "https://www.upliftventures.com",
  source: "Cold Call",
  clientClientName: "Mason Scott",
  companyName: "Uplift Ventures LLC",
  projects: "Mobile Apps",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 48,
  name: "Vanguard Innovations",
  phone: "+44-20-7946-0720",
  email: "info@vanguardinnovations.co.uk",
  fbId: "vanguard.innovations.fb",
  contactedFrom: "Email Campaign",
  website: "https://www.vanguardinnovations.co.uk",
  source: "Email",
  clientClientName: "Chloe Davies",
  companyName: "Vanguard Innovations Ltd.",
  projects: "AI Research",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 49,
  name: "Westend Technologies",
  phone: "+1-415-555-0135",
  email: "support@westendtech.com",
  fbId: "westend.tech.fb",
  contactedFrom: "Website",
  website: "https://www.westendtech.com",
  source: "Website",
  clientClientName: "Lucas Brown",
  companyName: "Westend Technologies LLC",
  projects: "DevOps",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
},
{
  id: 50,
  name: "Xcelerate Systems",
  phone: "+91-9123456788",
  email: "info@xceleratesystems.in",
  fbId: "xcelerate.systems.fb",
  contactedFrom: "LinkedIn",
  website: "https://www.xceleratesystems.in",
  source: "LinkedIn",
  clientClientName: "Pooja Mehta",
  companyName: "Xcelerate Systems Pvt Ltd",
  projects: "Cloud Migration",
  createdAt: new Date(),
  updatedAt: new Date(),
  pocId: 2,
}
]

const prismaClient = new PrismaClient();
async function main() {
  for (const client of seedClient) {
    await prismaClient.client.create({
      data: client,
    });
  }
  console.log("Seeding completed.");
}

main();
