// prisma/seed.mjs

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const data = [
    [
      {
        "name": "Acme Corporation",
        "phone": "9876543210",
        "email": "contact@acmecorp.com",
        "fbId": "acmecorp123",
        "contactedFrom": "LinkedIn",
        "website": "https://acmecorp.com",
        "source": "Referral",
        "clientClientName": "John Doe",
        "projects": "Website Development",
        "pocId": 2
      },
      {
        "name": "Bright Media Solutions",
        "phone": "9988776655",
        "email": "info@brightmedia.com",
        "fbId": "brightmedia789",
        "contactedFrom": "Facebook Ads",
        "website": "https://brightmedia.com",
        "source": "Website",
        "clientClientName": "Emily Watson",
        "projects": "Social Media Campaigns",
        "pocId": 3
      },
      {
        "name": "Zenith Tech",
        "phone": "9123456789",
        "email": "support@zenithtech.io",
        "fbId": "zenithtech22",
        "contactedFrom": "Email Campaign",
        "website": "https://zenithtech.io",
        "source": "Cold Call",
        "clientClientName": "Michael Chang",
        "projects": "App Development",
        "pocId": 1
      },
      {
        "name": "Skyline Digital",
        "phone": "9556677880",
        "email": "hello@skylinedigital.co",
        "fbId": "skyline.dg",
        "contactedFrom": "Instagram DM",
        "website": "https://skylinedigital.co",
        "source": "Social Media",
        "clientClientName": "Sophia Martinez",
        "projects": "SEO Optimization",
        "pocId": 4
      },
      {
        "name": "Greenfield Enterprises",
        "phone": "9898989898",
        "email": "contact@greenfield.com",
        "fbId": "greenfieldent",
        "contactedFrom": "Google Ads",
        "website": "https://greenfield.com",
        "source": "Advertisement",
        "clientClientName": "Rajesh Kumar",
        "projects": "Content Marketing",
        "pocId": 5
      },
      {
        "name": "NextGen Solutions",
        "phone": "8776655443",
        "email": "info@nextgensol.com",
        "fbId": "nextgensolutions",
        "contactedFrom": "Referral",
        "website": "https://nextgensol.com",
        "source": "Client Referral",
        "clientClientName": "Nisha Sharma",
        "projects": "Software Integration",
        "pocId": 2
      },
      {
        "name": "Pinnacle Ventures",
        "phone": "9112233445",
        "email": "sales@pinnaclev.com",
        "fbId": "pinnacleventures",
        "contactedFrom": "LinkedIn",
        "website": "https://pinnaclev.com",
        "source": "LinkedIn",
        "clientClientName": "Samuel Green",
        "projects": "Market Analysis",
        "pocId": 1
      },
      {
        "name": "Urban Dynamics",
        "phone": "9654321098",
        "email": "info@urbandynamics.in",
        "fbId": "urban.dynamics",
        "contactedFrom": "Google Search",
        "website": "https://urbandynamics.in",
        "source": "Search Engine",
        "clientClientName": "Arjun Mehta",
        "projects": "Branding Strategy",
        "pocId": 3
      },
      {
        "name": "Vortex Technologies",
        "phone": "9445566778",
        "email": "support@vortextech.com",
        "fbId": "vortextech",
        "contactedFrom": "Twitter",
        "website": "https://vortextech.com",
        "source": "Social Media",
        "clientClientName": "Laura Benson",
        "projects": "Cloud Solutions",
        "pocId": 4
      },
      {
        "name": "Fusion Innovations",
        "phone": "9778899001",
        "email": "hello@fusioninnovate.com",
        "fbId": "fusioninnovate",
        "contactedFrom": "Website Form",
        "website": "https://fusioninnovate.com",
        "source": "Website",
        "clientClientName": "Kunal Desai",
        "projects": "E-commerce Setup",
        "pocId": 5
      }
    ]
  ];

  const data2 = [[
    {
      "name": "BrightStar Media",
      "phone": "8765432109",
      "email": "contact@brightstarmedia.com",
      "pitchedFrom": "LinkedIn",
      "bankName": "HDFC Bank",
      "accountNumber": "123456789012",
      "ifscCode": "HDFC0001234",
      "paypalId": "brightstarmedia@paypal.com",
      "skypeId": "brightstar.skype",
      "upiId": "brightstar@hdfcbank",
      "category": "Agency"
    },
    {
      "name": "TechWave Solutions",
      "phone": "9988776654",
      "email": "hello@techwave.io",
      "pitchedFrom": "Email Outreach",
      "bankName": "ICICI Bank",
      "accountNumber": "987654321098",
      "ifscCode": "ICIC0004567",
      "paypalId": "techwave@paypal.com",
      "skypeId": "techwave.solutions",
      "upiId": "techwave@icici",
      "category": "Individual"
    },
    {
      "name": "MediaSphere",
      "phone": "9556677889",
      "email": "info@mediasphere.net",
      "pitchedFrom": "Website Inquiry",
      "bankName": "Axis Bank",
      "accountNumber": "112233445566",
      "ifscCode": "UTIB0007890",
      "paypalId": "mediasphere@paypal.com",
      "skypeId": "mediasphere.skype",
      "upiId": "mediasphere@axis",
      "category": "Agency"
    },
    {
      "name": "ContentCrate",
      "phone": "9123456780",
      "email": "support@contentcrate.com",
      "pitchedFrom": "Referral",
      "bankName": "State Bank of India",
      "accountNumber": "665544332211",
      "ifscCode": "SBIN0001122",
      "paypalId": "contentcrate@paypal.com",
      "skypeId": "content.crate",
      "upiId": "contentcrate@sbi",
      "category": "Individual"
    },
    {
      "name": "SEO Haven",
      "phone": "9898981234",
      "email": "seo@seohaven.org",
      "pitchedFrom": "Google Ads",
      "bankName": "Kotak Mahindra Bank",
      "accountNumber": "778899001122",
      "ifscCode": "KKBK0003344",
      "paypalId": "seohaven@paypal.com",
      "skypeId": "seohaven.skype",
      "upiId": "seohaven@kotak",
      "category": "Agency"
    },
    {
      "name": "WebNest Media",
      "phone": "9112233440",
      "email": "connect@webnestmedia.com",
      "pitchedFrom": "Instagram DM",
      "bankName": "Punjab National Bank",
      "accountNumber": "998877665544",
      "ifscCode": "PUNB0005566",
      "paypalId": "webnest@paypal.com",
      "skypeId": "webnest.media",
      "upiId": "webnest@pnb",
      "category": "Individual"
    },
    {
      "name": "PixelCraft Digital",
      "phone": "9654321090",
      "email": "info@pixelcraftdigital.io",
      "pitchedFrom": "Facebook Ads",
      "bankName": "Bank of Baroda",
      "accountNumber": "554433221100",
      "ifscCode": "BARB0XYZ123",
      "paypalId": "pixelcraft@paypal.com",
      "skypeId": "pixel.craft",
      "upiId": "pixelcraft@bob",
      "category": "Agency"
    },
    {
      "name": "AdEdge Marketing",
      "phone": "9445566777",
      "email": "support@adedge.com",
      "pitchedFrom": "Twitter Outreach",
      "bankName": "IDFC First Bank",
      "accountNumber": "334455667788",
      "ifscCode": "IDFB0001234",
      "paypalId": "adedge@paypal.com",
      "skypeId": "adedge.marketing",
      "upiId": "adedge@idfc",
      "category": "Individual"
    },
    {
      "name": "ContentHive",
      "phone": "9778899000",
      "email": "info@contenthive.net",
      "pitchedFrom": "Conference Meetup",
      "bankName": "Canara Bank",
      "accountNumber": "110022334455",
      "ifscCode": "CNRB0007890",
      "paypalId": "contenthive@paypal.com",
      "skypeId": "content.hive",
      "upiId": "contenthive@canarabank",
      "category": "Agency"
    },
    {
      "name": "LinkBoosters",
      "phone": "8776655440",
      "email": "contact@linkboosters.com",
      "pitchedFrom": "Upwork",
      "bankName": "Yes Bank",
      "accountNumber": "223344556677",
      "ifscCode": "YESB0001234",
      "paypalId": "linkboosters@paypal.com",
      "skypeId": "link.boosters",
      "upiId": "linkboosters@yesbank",
      "category": "Individual"
    }
  ]
  ]

  const data3 = [
    [
      {
        "website": "https://techinsights.io",
        "niche": "Technology",
        "contentCategories": "Gadgets, Software, AI",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 65,
        "pageAuthority": 58,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 50000,
        "spamScore": 8,
        "domainRating": 70,
        "socialMediaPosting": true,
        "costPrice": 150,
        "sellingPrice": 200,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 250,
        "linkInsertionCost": 50,
        "websiteRemark": "High traffic tech blog",
        "webIP": "192.168.1.10",
        "webCountry": "USA",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 60000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "UK",
        "semrushFirstCountryTraffic": 30000,
        "semrushSecondCountryTraffic": 15000,
        "semrushThirdCountryName": "India",
        "semrushThirdCountryTraffic": 8000,
        "semrushFourthCountryName": "Canada",
        "semrushFourthCountryTraffic": 5000,
        "semrushFifthCountryName": "Australia",
        "semrushFifthCountryTraffic": 3000,
        "similarwebTraffic": 58000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "All content is for informational purposes only.",
        "anchorText": true,
        "bannerImagePrice": 300,
        "costPriceUpdateDate": "2024-02-10T08:00:00Z",
        "pureCategory": "Tech",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 150,
        "semrushUpdateDate": "2024-02-05T08:00:00Z",
        "semrushOrganicTraffic": 60000,
        "semrushOrganicTrafficLastUpdated": "2024-02-12T08:00:00Z",
        "vendorId": 4
      },
      {
        "website": "https://healthnewsdaily.com",
        "niche": "Health",
        "contentCategories": "Nutrition, Wellness, Fitness",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 72,
        "pageAuthority": 64,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 42000,
        "spamScore": 5,
        "domainRating": 68,
        "socialMediaPosting": false,
        "costPrice": 120,
        "sellingPrice": 180,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 200,
        "linkInsertionCost": 40,
        "websiteRemark": "Trusted health advice portal",
        "webIP": "192.168.1.20",
        "webCountry": "UK",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 50000,
        "semrushFirstCountryName": "UK",
        "semrushSecondCountryName": "USA",
        "semrushFirstCountryTraffic": 25000,
        "semrushSecondCountryTraffic": 17000,
        "semrushThirdCountryName": "Canada",
        "semrushThirdCountryTraffic": 5000,
        "semrushFourthCountryName": "Australia",
        "semrushFourthCountryTraffic": 3000,
        "semrushFifthCountryName": "India",
        "semrushFifthCountryTraffic": 2000,
        "similarwebTraffic": 49000,
        "websiteType": "Language",
        "language": "English",
        "disclaimer": "Consult a healthcare professional for medical advice.",
        "anchorText": true,
        "bannerImagePrice": 250,
        "costPriceUpdateDate": "2024-01-25T08:00:00Z",
        "pureCategory": "Health",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 200,
        "semrushUpdateDate": "2024-01-20T08:00:00Z",
        "semrushOrganicTraffic": 50000,
        "semrushOrganicTrafficLastUpdated": "2024-02-01T08:00:00Z",
        "vendorId": 7
      },
      {
        "website": "https://casinoprofits.net",
        "niche": "Casino",
        "contentCategories": "Online Gaming, Betting, Poker",
        "siteClassification": "Casino",
        "priceCategory": "Paid",
        "domainAuthority": 58,
        "pageAuthority": 52,
        "linkAttribute": "Sponsored",
        "ahrefTraffic": 30000,
        "spamScore": 15,
        "domainRating": 62,
        "socialMediaPosting": true,
        "costPrice": 200,
        "sellingPrice": 280,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": 300,
        "cbdPrice": null,
        "linkInsertionCost": 70,
        "websiteRemark": "High DA casino website",
        "webIP": "192.168.1.30",
        "webCountry": "Malta",
        "turnAroundTime": "24 hours",
        "semrushTraffic": 35000,
        "semrushFirstCountryName": "Malta",
        "semrushSecondCountryName": "UK",
        "semrushFirstCountryTraffic": 18000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 5000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 34000,
        "websiteType": "PR",
        "language": "English",
        "disclaimer": "Gambling may be addictive. Play responsibly.",
        "anchorText": false,
        "bannerImagePrice": 350,
        "costPriceUpdateDate": "2024-02-01T08:00:00Z",
        "pureCategory": "Casino",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Multi",
        "numberOfLinks": 180,
        "semrushUpdateDate": "2024-01-30T08:00:00Z",
        "semrushOrganicTraffic": 35000,
        "semrushOrganicTrafficLastUpdated": "2024-02-10T08:00:00Z",
        "vendorId": 5
      },
      {
        "website": "https://cbdinsights.com",
        "niche": "CBD",
        "contentCategories": "CBD Products, Health Benefits, Legal Info",
        "siteClassification": "Cbd",
        "priceCategory": "Paid",
        "domainAuthority": 60,
        "pageAuthority": 55,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 28000,
        "spamScore": 9,
        "domainRating": 65,
        "socialMediaPosting": false,
        "costPrice": 180,
        "sellingPrice": 240,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 220,
        "linkInsertionCost": 60,
        "websiteRemark": "Premium CBD site",
        "webIP": "192.168.1.40",
        "webCountry": "USA",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 30000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "Canada",
        "semrushFirstCountryTraffic": 20000,
        "semrushSecondCountryTraffic": 7000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 3000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 29500,
        "websiteType": "Language",
        "language": "English",
        "disclaimer": "CBD products are not FDA approved.",
        "anchorText": true,
        "bannerImagePrice": 280,
        "costPriceUpdateDate": "2024-01-15T08:00:00Z",
        "pureCategory": "CBD",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 100,
        "semrushUpdateDate": "2024-01-12T08:00:00Z",
        "semrushOrganicTraffic": 30000,
        "semrushOrganicTrafficLastUpdated": "2024-02-08T08:00:00Z",
        "vendorId": 8
      },
      {
        "website": "https://gadgetbuzz.org",
        "niche": "Gadgets",
        "contentCategories": "Reviews, Comparisons, News",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 68,
        "pageAuthority": 62,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 55000,
        "spamScore": 6,
        "domainRating": 72,
        "socialMediaPosting": true,
        "costPrice": 130,
        "sellingPrice": 190,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 55,
        "websiteRemark": "Popular gadget review site",
        "webIP": "192.168.1.50",
        "webCountry": "India",
        "turnAroundTime": "36 hours",
        "semrushTraffic": 58000,
        "semrushFirstCountryName": "India",
        "semrushSecondCountryName": "USA",
        "semrushFirstCountryTraffic": 40000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 6000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 56000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Reviews are based on expert opinions.",
        "anchorText": true,
        "bannerImagePrice": 320,
        "costPriceUpdateDate": "2024-02-03T08:00:00Z",
        "pureCategory": "Gadgets",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 250,
        "semrushUpdateDate": "2024-02-01T08:00:00Z",
        "semrushOrganicTraffic": 58000,
        "semrushOrganicTrafficLastUpdated": "2024-02-11T08:00:00Z",
        "vendorId": 6
      }, 
      {
        "website": "https://digitaltrendsetters.com",
        "niche": "Digital Marketing",
        "contentCategories": "SEO, PPC, Social Media",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 70,
        "pageAuthority": 66,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 62000,
        "spamScore": 7,
        "domainRating": 74,
        "socialMediaPosting": true,
        "costPrice": 180,
        "sellingPrice": 250,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 300,
        "linkInsertionCost": 70,
        "websiteRemark": "Authority site in digital marketing",
        "webIP": "192.168.1.60",
        "webCountry": "USA",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 70000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "India",
        "semrushFirstCountryTraffic": 40000,
        "semrushSecondCountryTraffic": 20000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 10000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 69000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Content is for informational purposes only.",
        "anchorText": true,
        "bannerImagePrice": 400,
        "costPriceUpdateDate": "2024-02-14T08:00:00Z",
        "pureCategory": "Marketing",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 300,
        "semrushUpdateDate": "2024-02-10T08:00:00Z",
        "semrushOrganicTraffic": 70000,
        "semrushOrganicTrafficLastUpdated": "2024-02-15T08:00:00Z",
        "vendorId": 3
      },
      {
        "website": "https://fashionloop.com",
        "niche": "Fashion",
        "contentCategories": "Trends, Styles, Reviews",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 58,
        "pageAuthority": 54,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 45000,
        "spamScore": 10,
        "domainRating": 60,
        "socialMediaPosting": true,
        "costPrice": 150,
        "sellingPrice": 200,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 220,
        "linkInsertionCost": 50,
        "websiteRemark": "Trending fashion blog",
        "webIP": "192.168.1.61",
        "webCountry": "France",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 48000,
        "semrushFirstCountryName": "France",
        "semrushSecondCountryName": "Italy",
        "semrushFirstCountryTraffic": 30000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "Germany",
        "semrushThirdCountryTraffic": 6000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 46000,
        "websiteType": "Default",
        "language": "French",
        "disclaimer": "Fashion trends updated weekly.",
        "anchorText": true,
        "bannerImagePrice": 300,
        "costPriceUpdateDate": "2024-01-30T08:00:00Z",
        "pureCategory": "Fashion",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 250,
        "semrushUpdateDate": "2024-01-28T08:00:00Z",
        "semrushOrganicTraffic": 48000,
        "semrushOrganicTrafficLastUpdated": "2024-02-10T08:00:00Z",
        "vendorId": 8
      },
      {
        "website": "https://bettinglegends.com",
        "niche": "Casino",
        "contentCategories": "Betting, Casino Reviews, Tips",
        "siteClassification": "Casino",
        "priceCategory": "Paid",
        "domainAuthority": 55,
        "pageAuthority": 51,
        "linkAttribute": "Sponsored",
        "ahrefTraffic": 32000,
        "spamScore": 18,
        "domainRating": 58,
        "socialMediaPosting": false,
        "costPrice": 210,
        "sellingPrice": 280,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": 320,
        "cbdPrice": null,
        "linkInsertionCost": 60,
        "websiteRemark": "High-quality casino review platform",
        "webIP": "192.168.1.62",
        "webCountry": "Cyprus",
        "turnAroundTime": "24 hours",
        "semrushTraffic": 33000,
        "semrushFirstCountryName": "Cyprus",
        "semrushSecondCountryName": "UK",
        "semrushFirstCountryTraffic": 20000,
        "semrushSecondCountryTraffic": 10000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 3000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 32000,
        "websiteType": "PR",
        "language": "English",
        "disclaimer": "Bet responsibly.",
        "anchorText": false,
        "bannerImagePrice": 350,
        "costPriceUpdateDate": "2024-01-18T08:00:00Z",
        "pureCategory": "Casino",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Multi",
        "numberOfLinks": 180,
        "semrushUpdateDate": "2024-01-15T08:00:00Z",
        "semrushOrganicTraffic": 33000,
        "semrushOrganicTrafficLastUpdated": "2024-02-05T08:00:00Z",
        "vendorId": 9
      },
      {
        "website": "https://techbytes.co",
        "niche": "Technology",
        "contentCategories": "Gadgets, AI, Startups",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 66,
        "pageAuthority": 59,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 54000,
        "spamScore": 6,
        "domainRating": 71,
        "socialMediaPosting": true,
        "costPrice": 160,
        "sellingPrice": 210,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 250,
        "linkInsertionCost": 55,
        "websiteRemark": "Emerging tech site with high engagement",
        "webIP": "192.168.1.63",
        "webCountry": "India",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 58000,
        "semrushFirstCountryName": "India",
        "semrushSecondCountryName": "USA",
        "semrushFirstCountryTraffic": 35000,
        "semrushSecondCountryTraffic": 15000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 8000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 56000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Tech insights for all readers.",
        "anchorText": true,
        "bannerImagePrice": 320,
        "costPriceUpdateDate": "2024-02-07T08:00:00Z",
        "pureCategory": "Tech",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 200,
        "semrushUpdateDate": "2024-02-01T08:00:00Z",
        "semrushOrganicTraffic": 58000,
        "semrushOrganicTrafficLastUpdated": "2024-02-13T08:00:00Z",
        "vendorId": 6
      },
      {
        "website": "https://wellnessjourney.com",
        "niche": "Health",
        "contentCategories": "Yoga, Nutrition, Mental Health",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 62,
        "pageAuthority": 57,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 43000,
        "spamScore": 5,
        "domainRating": 67,
        "socialMediaPosting": false,
        "costPrice": 140,
        "sellingPrice": 190,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 200,
        "linkInsertionCost": 45,
        "websiteRemark": "Popular health and wellness blog",
        "webIP": "192.168.1.64",
        "webCountry": "Australia",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 47000,
        "semrushFirstCountryName": "Australia",
        "semrushSecondCountryName": "India",
        "semrushFirstCountryTraffic": 28000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 7000,
        "semrushFourthCountryName": null,
        "semrushFourthCountryTraffic": null,
        "semrushFifthCountryName": null,
        "semrushFifthCountryTraffic": null,
        "similarwebTraffic": 45000,
        "websiteType": "Language",
        "language": "English",
        "disclaimer": "Consult a professional for health advice.",
        "anchorText": true,
        "bannerImagePrice": 280,
        "costPriceUpdateDate": "2024-01-27T08:00:00Z",
        "pureCategory": "Health",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 180,
        "semrushUpdateDate": "2024-01-23T08:00:00Z",
        "semrushOrganicTraffic": 47000,
        "semrushOrganicTrafficLastUpdated": "2024-02-09T08:00:00Z",
        "vendorId": 4
      }, 
      {
        "website": "https://gaminghubnow.com",
        "niche": "Gaming",
        "contentCategories": "Reviews, Tutorials, News",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 61,
        "pageAuthority": 55,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 39000,
        "spamScore": 6,
        "domainRating": 65,
        "socialMediaPosting": true,
        "costPrice": 160,
        "sellingPrice": 220,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 50,
        "websiteRemark": "Top gaming news and reviews",
        "webIP": "192.168.1.65",
        "webCountry": "USA",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 42000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "Canada",
        "semrushFirstCountryTraffic": 25000,
        "semrushSecondCountryTraffic": 10000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 7000,
        "similarwebTraffic": 41000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Gaming content for all ages.",
        "anchorText": true,
        "bannerImagePrice": 300,
        "costPriceUpdateDate": "2024-02-12T08:00:00Z",
        "pureCategory": "Gaming",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 150,
        "semrushUpdateDate": "2024-02-05T08:00:00Z",
        "semrushOrganicTraffic": 42000,
        "semrushOrganicTrafficLastUpdated": "2024-02-14T08:00:00Z",
        "vendorId": 5
      },
      {
        "website": "https://foodielicious.net",
        "niche": "Food",
        "contentCategories": "Recipes, Reviews, Trends",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 64,
        "pageAuthority": 58,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 35000,
        "spamScore": 5,
        "domainRating": 68,
        "socialMediaPosting": true,
        "costPrice": 150,
        "sellingPrice": 210,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 40,
        "websiteRemark": "Popular food blog with high engagement",
        "webIP": "192.168.1.66",
        "webCountry": "India",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 38000,
        "semrushFirstCountryName": "India",
        "semrushSecondCountryName": "USA",
        "semrushFirstCountryTraffic": 20000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "Australia",
        "semrushThirdCountryTraffic": 6000,
        "similarwebTraffic": 37000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Food content created by experts.",
        "anchorText": true,
        "bannerImagePrice": 270,
        "costPriceUpdateDate": "2024-01-31T08:00:00Z",
        "pureCategory": "Food",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 180,
        "semrushUpdateDate": "2024-01-28T08:00:00Z",
        "semrushOrganicTraffic": 38000,
        "semrushOrganicTrafficLastUpdated": "2024-02-09T08:00:00Z",
        "vendorId": 7
      },
      {
        "website": "https://financefocusworld.com",
        "niche": "Finance",
        "contentCategories": "Investments, Markets, Analysis",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 69,
        "pageAuthority": 63,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 58000,
        "spamScore": 4,
        "domainRating": 72,
        "socialMediaPosting": false,
        "costPrice": 180,
        "sellingPrice": 240,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 70,
        "websiteRemark": "Trusted financial insights site",
        "webIP": "192.168.1.67",
        "webCountry": "UK",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 60000,
        "semrushFirstCountryName": "UK",
        "semrushSecondCountryName": "India",
        "semrushFirstCountryTraffic": 30000,
        "semrushSecondCountryTraffic": 20000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 10000,
        "similarwebTraffic": 59000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Financial advice is not guaranteed.",
        "anchorText": true,
        "bannerImagePrice": 320,
        "costPriceUpdateDate": "2024-02-08T08:00:00Z",
        "pureCategory": "Finance",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 220,
        "semrushUpdateDate": "2024-02-02T08:00:00Z",
        "semrushOrganicTraffic": 60000,
        "semrushOrganicTrafficLastUpdated": "2024-02-12T08:00:00Z",
        "vendorId": 9
      },
      {
        "website": "https://beautyandglow.com",
        "niche": "Beauty",
        "contentCategories": "Skincare, Makeup, Trends",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 55,
        "pageAuthority": 52,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 29000,
        "spamScore": 8,
        "domainRating": 60,
        "socialMediaPosting": true,
        "costPrice": 130,
        "sellingPrice": 180,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 35,
        "websiteRemark": "Upcoming beauty blog",
        "webIP": "192.168.1.68",
        "webCountry": "France",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 31000,
        "semrushFirstCountryName": "France",
        "semrushSecondCountryName": "Italy",
        "semrushFirstCountryTraffic": 18000,
        "semrushSecondCountryTraffic": 9000,
        "semrushThirdCountryName": "Germany",
        "semrushThirdCountryTraffic": 4000,
        "similarwebTraffic": 30000,
        "websiteType": "Default",
        "language": "French",
        "disclaimer": "Beauty tips from professionals.",
        "anchorText": true,
        "bannerImagePrice": 250,
        "costPriceUpdateDate": "2024-01-20T08:00:00Z",
        "pureCategory": "Beauty",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 150,
        "semrushUpdateDate": "2024-01-15T08:00:00Z",
        "semrushOrganicTraffic": 31000,
        "semrushOrganicTrafficLastUpdated": "2024-02-05T08:00:00Z",
        "vendorId": 4
      },
      {
        "website": "https://adventurerspirit.com",
        "niche": "Travel",
        "contentCategories": "Destinations, Reviews, Tips",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 63,
        "pageAuthority": 59,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 45000,
        "spamScore": 5,
        "domainRating": 67,
        "socialMediaPosting": false,
        "costPrice": 170,
        "sellingPrice": 230,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 55,
        "websiteRemark": "Inspiring travel stories",
        "webIP": "192.168.1.69",
        "webCountry": "Australia",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 47000,
        "semrushFirstCountryName": "Australia",
        "semrushSecondCountryName": "India",
        "semrushFirstCountryTraffic": 25000,
        "semrushSecondCountryTraffic": 15000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 7000,
        "similarwebTraffic": 46000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Travel at your own risk.",
        "anchorText": true,
        "bannerImagePrice": 300,
        "costPriceUpdateDate": "2024-02-03T08:00:00Z",
        "pureCategory": "Travel",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 180,
        "semrushUpdateDate": "2024-01-28T08:00:00Z",
        "semrushOrganicTraffic": 47000,
        "semrushOrganicTrafficLastUpdated": "2024-02-10T08:00:00Z",
        "vendorId": 6
      },
      {
        "website": "https://sportsmaniahub.com",
        "niche": "Sports",
        "contentCategories": "Football, Cricket, NBA",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 68,
        "pageAuthority": 62,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 53000,
        "spamScore": 7,
        "domainRating": 71,
        "socialMediaPosting": true,
        "costPrice": 175,
        "sellingPrice": 230,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 65,
        "websiteRemark": "Popular sports analysis site",
        "webIP": "192.168.1.70",
        "webCountry": "India",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 55000,
        "semrushFirstCountryName": "India",
        "semrushSecondCountryName": "UK",
        "semrushFirstCountryTraffic": 30000,
        "semrushSecondCountryTraffic": 18000,
        "semrushThirdCountryName": "Australia",
        "semrushThirdCountryTraffic": 7000,
        "similarwebTraffic": 54000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Sports opinions may vary.",
        "anchorText": true,
        "bannerImagePrice": 320,
        "costPriceUpdateDate": "2024-02-14T08:00:00Z",
        "pureCategory": "Sports",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 210,
        "semrushUpdateDate": "2024-02-08T08:00:00Z",
        "semrushOrganicTraffic": 55000,
        "semrushOrganicTrafficLastUpdated": "2024-02-15T08:00:00Z",
        "vendorId": 9
      },
      {
        "website": "https://cryptovista.io",
        "niche": "Finance",
        "contentCategories": "Cryptocurrency, Blockchain, NFTs",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 72,
        "pageAuthority": 65,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 62000,
        "spamScore": 5,
        "domainRating": 74,
        "socialMediaPosting": false,
        "costPrice": 190,
        "sellingPrice": 260,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 75,
        "websiteRemark": "Leading crypto insights platform",
        "webIP": "192.168.1.71",
        "webCountry": "USA",
        "turnAroundTime": "36 hours",
        "semrushTraffic": 65000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "Canada",
        "semrushFirstCountryTraffic": 35000,
        "semrushSecondCountryTraffic": 20000,
        "semrushThirdCountryName": "India",
        "semrushThirdCountryTraffic": 10000,
        "similarwebTraffic": 64000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Crypto investments are risky.",
        "anchorText": true,
        "bannerImagePrice": 400,
        "costPriceUpdateDate": "2024-02-10T08:00:00Z",
        "pureCategory": "Crypto",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 230,
        "semrushUpdateDate": "2024-02-05T08:00:00Z",
        "semrushOrganicTraffic": 65000,
        "semrushOrganicTrafficLastUpdated": "2024-02-12T08:00:00Z",
        "vendorId": 4
      },
      {
        "website": "https://wanderlustgram.com",
        "niche": "Travel",
        "contentCategories": "Photography, Destinations, Culture",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 60,
        "pageAuthority": 54,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 36000,
        "spamScore": 6,
        "domainRating": 64,
        "socialMediaPosting": true,
        "costPrice": 150,
        "sellingPrice": 200,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 45,
        "websiteRemark": "Inspirational travel stories",
        "webIP": "192.168.1.72",
        "webCountry": "Australia",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 39000,
        "semrushFirstCountryName": "Australia",
        "semrushSecondCountryName": "India",
        "semrushFirstCountryTraffic": 22000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 5000,
        "similarwebTraffic": 38000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Travel responsibly.",
        "anchorText": true,
        "bannerImagePrice": 280,
        "costPriceUpdateDate": "2024-01-30T08:00:00Z",
        "pureCategory": "Travel",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 160,
        "semrushUpdateDate": "2024-01-25T08:00:00Z",
        "semrushOrganicTraffic": 39000,
        "semrushOrganicTrafficLastUpdated": "2024-02-08T08:00:00Z",
        "vendorId": 8
      },
      {
        "website": "https://greenearthstories.com",
        "niche": "Environment",
        "contentCategories": "Sustainability, Climate, Renewable Energy",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 65,
        "pageAuthority": 59,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 42000,
        "spamScore": 4,
        "domainRating": 68,
        "socialMediaPosting": false,
        "costPrice": 165,
        "sellingPrice": 220,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 230,
        "linkInsertionCost": 60,
        "websiteRemark": "Eco-friendly insights and news",
        "webIP": "192.168.1.73",
        "webCountry": "Germany",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 44000,
        "semrushFirstCountryName": "Germany",
        "semrushSecondCountryName": "UK",
        "semrushFirstCountryTraffic": 25000,
        "semrushSecondCountryTraffic": 14000,
        "semrushThirdCountryName": "USA",
        "semrushThirdCountryTraffic": 5000,
        "similarwebTraffic": 43000,
        "websiteType": "Default",
        "language": "German",
        "disclaimer": "Support a sustainable planet.",
        "anchorText": true,
        "bannerImagePrice": 310,
        "costPriceUpdateDate": "2024-01-25T08:00:00Z",
        "pureCategory": "Environment",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 190,
        "semrushUpdateDate": "2024-01-20T08:00:00Z",
        "semrushOrganicTraffic": 44000,
        "semrushOrganicTrafficLastUpdated": "2024-02-04T08:00:00Z",
        "vendorId": 5
      },
      {
        "website": "https://fashiondive.net",
        "niche": "Fashion",
        "contentCategories": "Runway, Trends, Brands",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 59,
        "pageAuthority": 53,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 31000,
        "spamScore": 8,
        "domainRating": 63,
        "socialMediaPosting": true,
        "costPrice": 140,
        "sellingPrice": 200,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 35,
        "websiteRemark": "Emerging fashion portal",
        "webIP": "192.168.1.74",
        "webCountry": "France",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 34000,
        "semrushFirstCountryName": "France",
        "semrushSecondCountryName": "Italy",
        "semrushFirstCountryTraffic": 21000,
        "semrushSecondCountryTraffic": 9000,
        "semrushThirdCountryName": "Germany",
        "semrushThirdCountryTraffic": 4000,
        "similarwebTraffic": 33000,
        "websiteType": "Default",
        "language": "French",
        "disclaimer": "Fashion insights updated weekly.",
        "anchorText": true,
        "bannerImagePrice": 250,
        "costPriceUpdateDate": "2024-02-01T08:00:00Z",
        "pureCategory": "Fashion",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 170,
        "semrushUpdateDate": "2024-01-28T08:00:00Z",
        "semrushOrganicTraffic": 34000,
        "semrushOrganicTrafficLastUpdated": "2024-02-07T08:00:00Z",
        "vendorId": 3
      },
      {
        "website": "https://fitlifehacks.com",
        "niche": "Health",
        "contentCategories": "Fitness, Nutrition, Wellness",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 63,
        "pageAuthority": 58,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 40000,
        "spamScore": 5,
        "domainRating": 66,
        "socialMediaPosting": true,
        "costPrice": 170,
        "sellingPrice": 220,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 210,
        "linkInsertionCost": 60,
        "websiteRemark": "Popular fitness and wellness blog",
        "webIP": "192.168.1.75",
        "webCountry": "USA",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 43000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "Canada",
        "semrushFirstCountryTraffic": 25000,
        "semrushSecondCountryTraffic": 12000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 6000,
        "similarwebTraffic": 42000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Fitness advice by experts.",
        "anchorText": true,
        "bannerImagePrice": 300,
        "costPriceUpdateDate": "2024-02-12T08:00:00Z",
        "pureCategory": "Health",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 190,
        "semrushUpdateDate": "2024-02-08T08:00:00Z",
        "semrushOrganicTraffic": 43000,
        "semrushOrganicTrafficLastUpdated": "2024-02-15T08:00:00Z",
        "vendorId": 4
      },
      {
        "website": "https://gadgetfreaks.com",
        "niche": "Technology",
        "contentCategories": "Gadget Reviews, Tech News, Comparisons",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 70,
        "pageAuthority": 64,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 58000,
        "spamScore": 7,
        "domainRating": 73,
        "socialMediaPosting": true,
        "costPrice": 200,
        "sellingPrice": 260,
        "discount": 20,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": 250,
        "linkInsertionCost": 75,
        "websiteRemark": "Trusted gadget review platform",
        "webIP": "192.168.1.76",
        "webCountry": "India",
        "turnAroundTime": "36 hours",
        "semrushTraffic": 60000,
        "semrushFirstCountryName": "India",
        "semrushSecondCountryName": "USA",
        "semrushFirstCountryTraffic": 35000,
        "semrushSecondCountryTraffic": 18000,
        "semrushThirdCountryName": "UK",
        "semrushThirdCountryTraffic": 7000,
        "similarwebTraffic": 59000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Tech reviews are subjective.",
        "anchorText": true,
        "bannerImagePrice": 350,
        "costPriceUpdateDate": "2024-02-10T08:00:00Z",
        "pureCategory": "Technology",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 250,
        "semrushUpdateDate": "2024-02-06T08:00:00Z",
        "semrushOrganicTraffic": 60000,
        "semrushOrganicTrafficLastUpdated": "2024-02-13T08:00:00Z",
        "vendorId": 6
      },
      {
        "website": "https://cinemascene.net",
        "niche": "Entertainment",
        "contentCategories": "Movies, TV Shows, Celebrity News",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 58,
        "pageAuthority": 52,
        "linkAttribute": "NoFollow",
        "ahrefTraffic": 32000,
        "spamScore": 6,
        "domainRating": 61,
        "socialMediaPosting": true,
        "costPrice": 140,
        "sellingPrice": 190,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 40,
        "websiteRemark": "Latest entertainment buzz",
        "webIP": "192.168.1.77",
        "webCountry": "UK",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 35000,
        "semrushFirstCountryName": "UK",
        "semrushSecondCountryName": "USA",
        "semrushFirstCountryTraffic": 20000,
        "semrushSecondCountryTraffic": 10000,
        "semrushThirdCountryName": "Canada",
        "semrushThirdCountryTraffic": 5000,
        "similarwebTraffic": 34000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Entertainment content only.",
        "anchorText": true,
        "bannerImagePrice": 250,
        "costPriceUpdateDate": "2024-02-05T08:00:00Z",
        "pureCategory": "Entertainment",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 170,
        "semrushUpdateDate": "2024-01-30T08:00:00Z",
        "semrushOrganicTraffic": 35000,
        "semrushOrganicTrafficLastUpdated": "2024-02-09T08:00:00Z",
        "vendorId": 8
      },
      {
        "website": "https://veganplate.org",
        "niche": "Food",
        "contentCategories": "Vegan Recipes, Reviews, Nutrition",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 55,
        "pageAuthority": 50,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 28000,
        "spamScore": 4,
        "domainRating": 58,
        "socialMediaPosting": true,
        "costPrice": 130,
        "sellingPrice": 180,
        "discount": 15,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 35,
        "websiteRemark": "Popular vegan food blog",
        "webIP": "192.168.1.78",
        "webCountry": "Germany",
        "turnAroundTime": "72 hours",
        "semrushTraffic": 30000,
        "semrushFirstCountryName": "Germany",
        "semrushSecondCountryName": "France",
        "semrushFirstCountryTraffic": 17000,
        "semrushSecondCountryTraffic": 10000,
        "semrushThirdCountryName": "Italy",
        "semrushThirdCountryTraffic": 3000,
        "similarwebTraffic": 29000,
        "websiteType": "Default",
        "language": "German",
        "disclaimer": "Vegan content curated by experts.",
        "anchorText": true,
        "bannerImagePrice": 240,
        "costPriceUpdateDate": "2024-02-01T08:00:00Z",
        "pureCategory": "Food",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "AlmostPure",
        "numberOfLinks": 160,
        "semrushUpdateDate": "2024-01-28T08:00:00Z",
        "semrushOrganicTraffic": 30000,
        "semrushOrganicTrafficLastUpdated": "2024-02-06T08:00:00Z",
        "vendorId": 9
      },
      {
        "website": "https://financetrailblazers.com",
        "niche": "Finance",
        "contentCategories": "Investments, Markets, Personal Finance",
        "siteClassification": "Normal",
        "priceCategory": "Paid",
        "domainAuthority": 71,
        "pageAuthority": 65,
        "linkAttribute": "DoFollow",
        "ahrefTraffic": 61000,
        "spamScore": 5,
        "domainRating": 74,
        "socialMediaPosting": false,
        "costPrice": 190,
        "sellingPrice": 250,
        "discount": 10,
        "adultPrice": null,
        "casinoAdultPrice": null,
        "cbdPrice": null,
        "linkInsertionCost": 70,
        "websiteRemark": "Leading financial advice site",
        "webIP": "192.168.1.79",
        "webCountry": "USA",
        "turnAroundTime": "48 hours",
        "semrushTraffic": 63000,
        "semrushFirstCountryName": "USA",
        "semrushSecondCountryName": "UK",
        "semrushFirstCountryTraffic": 35000,
        "semrushSecondCountryTraffic": 20000,
        "semrushThirdCountryName": "India",
        "semrushThirdCountryTraffic": 8000,
        "similarwebTraffic": 62000,
        "websiteType": "Default",
        "language": "English",
        "disclaimer": "Finance advice by experts.",
        "anchorText": true,
        "bannerImagePrice": 380,
        "costPriceUpdateDate": "2024-02-08T08:00:00Z",
        "pureCategory": "Finance",
        "availability": true,
        "isIndexed": true,
        "websiteStatus": "Normal",
        "websiteQuality": "Pure",
        "numberOfLinks": 240,
        "semrushUpdateDate": "2024-02-03T08:00:00Z",
        "semrushOrganicTraffic": 63000,
        "semrushOrganicTrafficLastUpdated": "2024-02-11T08:00:00Z",
        "vendorId": 5
      }
    ]
  ]

  const data4 = [
    [
      {
        "orderDate": "2024-01-12T10:30:00Z",
        "orderStatus": "Pending",
        "vendorAssignedDate": "2024-01-13T12:00:00Z",
        "orderStatusUpdateDate": "2024-01-14T14:30:00Z",
        "publishDate": null,
        "publishURL": null,
        "orderRemark": "Initial discussion with vendor in progress.",
        "mainRemark": "Awaiting vendor confirmation.",
        "clientPaymentRemark": "Payment expected after project completion.",
        "clientContentCost": 15000,
        "clientProposedAmount": 20000,
        "clientPaymentStatus": "Pending",
        "clientReceivedAmount": null,
        "clientPaymentDate": null,
        "vendorInvoiceStatus": "Pending",
        "vendorPaymentStatus": "Unpaid",
        "vendorPaymentDate": null,
        "vendorPaymentAmount": null,
        "invoiceNumber": "INV-202401-001",
        "costPriceWithGST": 18000,
        "indexedScreenShotLink": null,
        "siteId": 5,
        "salesPersonId": 1,
        "clientId": 12
      },
      {
        "orderDate": "2024-01-18T11:45:00Z",
        "orderStatus": "Given",
        "vendorAssignedDate": "2024-01-19T10:00:00Z",
        "orderStatusUpdateDate": "2024-01-20T15:00:00Z",
        "publishDate": null,
        "publishURL": null,
        "orderRemark": "Vendor assigned and working on content.",
        "mainRemark": "Expected delivery in 3 days.",
        "clientPaymentRemark": "Partial payment received.",
        "clientContentCost": 20000,
        "clientProposedAmount": 25000,
        "clientPaymentStatus": "PartiallyReceived",
        "clientReceivedAmount": 10000,
        "clientPaymentDate": "2024-01-25T09:30:00Z",
        "vendorInvoiceStatus": "Ask",
        "vendorPaymentStatus": "PartiallyPaid",
        "vendorPaymentDate": "2024-01-28T12:00:00Z",
        "vendorPaymentAmount": 12000,
        "invoiceNumber": "INV-202401-002",
        "costPriceWithGST": 21000,
        "indexedScreenShotLink": "https://drive.link/screenshot-001",
        "siteId": 15,
        "salesPersonId": 1,
        "clientId": 13
      },
      {
        "orderDate": "2024-01-22T14:15:00Z",
        "orderStatus": "Publish",
        "vendorAssignedDate": "2024-01-23T11:00:00Z",
        "orderStatusUpdateDate": "2024-01-24T16:45:00Z",
        "publishDate": "2024-01-25T09:00:00Z",
        "publishURL": "https://example.com/article-123",
        "orderRemark": "Content published successfully.",
        "mainRemark": "Client satisfied with the outcome.",
        "clientPaymentRemark": "Payment received in full.",
        "clientContentCost": 18000,
        "clientProposedAmount": 22000,
        "clientPaymentStatus": "Received",
        "clientReceivedAmount": 22000,
        "clientPaymentDate": "2024-01-30T10:30:00Z",
        "vendorInvoiceStatus": "Received",
        "vendorPaymentStatus": "Paid",
        "vendorPaymentDate": "2024-02-02T13:00:00Z",
        "vendorPaymentAmount": 15000,
        "invoiceNumber": "INV-202401-003",
        "costPriceWithGST": 16500,
        "indexedScreenShotLink": "https://drive.link/screenshot-002",
        "siteId": 8,
        "salesPersonId": 1,
        "clientId": 14
      },
      {
        "orderDate": "2024-02-01T09:20:00Z",
        "orderStatus": "NotPublish",
        "vendorAssignedDate": "2024-02-02T12:30:00Z",
        "orderStatusUpdateDate": "2024-02-03T15:15:00Z",
        "publishDate": null,
        "publishURL": null,
        "orderRemark": "Content rejected by client.",
        "mainRemark": "Need to revise and resubmit.",
        "clientPaymentRemark": "Payment on hold until publication.",
        "clientContentCost": 17000,
        "clientProposedAmount": 21000,
        "clientPaymentStatus": "NotReceived",
        "clientReceivedAmount": null,
        "clientPaymentDate": null,
        "vendorInvoiceStatus": "Pending",
        "vendorPaymentStatus": "Hold",
        "vendorPaymentDate": null,
        "vendorPaymentAmount": null,
        "invoiceNumber": "INV-202402-001",
        "costPriceWithGST": 19000,
        "indexedScreenShotLink": null,
        "siteId": 21,
        "salesPersonId": 1,
        "clientId": 15
      },
      {
        "orderDate": "2024-02-05T13:00:00Z",
        "orderStatus": "Replacement",
        "vendorAssignedDate": "2024-02-06T14:30:00Z",
        "orderStatusUpdateDate": "2024-02-07T16:00:00Z",
        "publishDate": "2024-02-08T09:30:00Z",
        "publishURL": "https://example.com/revised-article-456",
        "orderRemark": "Content replaced as per client request.",
        "mainRemark": "Successful replacement completed.",
        "clientPaymentRemark": "Payment adjustment done.",
        "clientContentCost": 16000,
        "clientProposedAmount": 20000,
        "clientPaymentStatus": "PartiallyReceived",
        "clientReceivedAmount": 15000,
        "clientPaymentDate": "2024-02-10T11:30:00Z",
        "vendorInvoiceStatus": "Given",
        "vendorPaymentStatus": "PartiallyPaid",
        "vendorPaymentDate": "2024-02-12T14:00:00Z",
        "vendorPaymentAmount": 14000,
        "invoiceNumber": "INV-202402-002",
        "costPriceWithGST": 18500,
        "indexedScreenShotLink": "https://drive.link/screenshot-003",
        "siteId": 19,
        "salesPersonId": 1,
        "clientId": 16
      }
    ]  
    

  ]

    await prisma.order.createMany({
      data: data4[0].map((client) => ({
        ...client,
      }))
    });
    console.log("Client data seeded successfully!");
    await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
