import { PrismaClient } from "@prisma/client";
const siteSeed = [
  {
    id: 1,
    website: "alphaexample.com",
    niche: "Technology",
    contentCategories: "Tech News, Gadgets",
    siteClassification: "Normal",
    priceCategory: "Paid",
    domainAuthority: 45,
    pageAuthority: 38,
    linkAttribute: "DoFollow",
    ahrefTraffic: 12000,
    spamScore: 3,
    domainRating: 50,
    socialMediaPosting: true,
    sampleURL: "https://alphaexample.com/sample",
    costPrice: 500,
    costPriceValidFrom: new Date("2023-01-15"),
    costPriceValidTo: new Date("2023-12-31"),
    sellingPrice: 700,
    discount: 10,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 100,
    websiteRemark: "High engagement",
    webIP: "192.168.1.1",
    webCountry: "USA",
    turnAroundTime: "24h",
    semrushTraffic: BigInt(150000),
    semrushFirstCountryName: "USA",
    semrushSecondCountryName: "Canada",
    semrushFirstCountryTraffic: 80000,
    semrushSecondCountryTraffic: 40000,
    semrushThirdCountryName: "UK",
    semrushThirdCountryTraffic: 15000,
    semrushFourthCountryName: "Australia",
    semrushFourthCountryTraffic: 10000,
    semrushFifthCountryName: "Germany",
    semrushFifthCountryTraffic: 5000,
    similarwebTraffic: 140000,
    siteUpdateDate: new Date("2024-04-01"),
    domainAuthorityUpdateDate: new Date("2024-04-01"),
    websiteType: "Default",
    language: "English",
    disclaimer: "Standard disclaimer applies.",
    anchorText: true,
    bannerImagePrice: 250,
    costPriceUpdateDate: new Date("2024-01-01"),
    pureCategory: "Technology",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "Pure",
    numberOfLinks: 120,
    semrushUpdateDate: new Date("2024-04-01"),
    semrushOrganicTraffic: 140000,
    semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 12,
    pocId: 2,
  },
  {
    id: 2,
    website: "betacreative.org",

    niche: "Creative Arts",
    contentCategories: "Design, Photography",
    siteClassification: "Organic",
    priceCategory: "Free",
    domainAuthority: 38,
    pageAuthority: 30,
    linkAttribute: "NoFollow",
    ahrefTraffic: 5000,
    spamScore: 1,
    domainRating: 40,
    socialMediaPosting: false,
    sampleURL: "https://betacreative.org/sample",
    costPrice: 0,
    costPriceValidFrom: null,
    costPriceValidTo: null,
    sellingPrice: null,
    discount: null,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 0,
    websiteRemark: "Organic reach growing steadily",
    webIP: "192.168.2.2",
    webCountry: "UK",
    turnAroundTime: "48h",
    semrushTraffic: BigInt(50000),
    semrushFirstCountryName: "UK",
    semrushSecondCountryName: "France",
    semrushFirstCountryTraffic: 30000,
    semrushSecondCountryTraffic: 10000,
    semrushThirdCountryName: "Germany",
    semrushThirdCountryTraffic: 5000,
    semrushFourthCountryName: "Italy",
    semrushFourthCountryTraffic: 3000,
    semrushFifthCountryName: "Spain",
    semrushFifthCountryTraffic: 2000,
    similarwebTraffic: 48000,
    siteUpdateDate: new Date("2024-03-20"),
    domainAuthorityUpdateDate: new Date("2024-03-18"),
    websiteType: "PR",
    language: "English",
    disclaimer: "Content is user-generated.",
    anchorText: false,
    bannerImagePrice: 0,
    costPriceUpdateDate: null,
    pureCategory: "Arts",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "AlmostPure",
    numberOfLinks: 90,
    semrushUpdateDate: new Date("2024-03-20"),
    semrushOrganicTraffic: 48000,
    semrushOrganicTrafficLastUpdated: new Date("2024-03-20"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 27,
    pocId: 2,
  },
  {
    id: 3,
    website: "gammacrypto.io",
    niche: "Cryptocurrency",
    contentCategories: "Trading, Analysis",
    siteClassification: "Crypto",
    priceCategory: "Paid",
    domainAuthority: 60,
    pageAuthority: 55,
    linkAttribute: "Sponsored",
    ahrefTraffic: 25000,
    spamScore: 5,
    domainRating: 65,
    socialMediaPosting: true,
    sampleURL: "https://gammacrypto.io/sample",
    costPrice: 900,
    costPriceValidFrom: new Date("2023-05-01"),
    costPriceValidTo: new Date("2024-05-01"),
    sellingPrice: 1200,
    discount: 15,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 200,
    websiteRemark: "High conversion rates",
    webIP: "172.217.11.14",
    webCountry: "Singapore",
    turnAroundTime: "12h",
    semrushTraffic: BigInt(70000),
    semrushFirstCountryName: "Singapore",
    semrushSecondCountryName: "USA",
    semrushFirstCountryTraffic: 35000,
    semrushSecondCountryTraffic: 20000,
    semrushThirdCountryName: "UK",
    semrushThirdCountryTraffic: 7000,
    semrushFourthCountryName: "Australia",
    semrushFourthCountryTraffic: 3000,
    semrushFifthCountryName: "Canada",
    semrushFifthCountryTraffic: 1000,
    similarwebTraffic: 68000,
    siteUpdateDate: new Date("2024-04-10"),
    domainAuthorityUpdateDate: new Date("2024-04-10"),
    websiteType: "PR_Brand",
    language: "English",
    disclaimer: "Crypto trading involves risk.",
    anchorText: true,
    bannerImagePrice: 500,
    costPriceUpdateDate: new Date("2024-01-10"),
    pureCategory: "Finance",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "Pure",
    numberOfLinks: 150,
    semrushUpdateDate: new Date("2024-04-10"),
    semrushOrganicTraffic: 68000,
    semrushOrganicTrafficLastUpdated: new Date("2024-04-10"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 3,
    pocId: 2,
  },
  {
    id: 4,
    website: "deltacasino.net",
    niche: "Casino",
    contentCategories: "Games, Bonuses",
    siteClassification: "Casino",
    priceCategory: "Exchange",
    domainAuthority: 52,
    pageAuthority: 48,
    linkAttribute: "DoFollow",
    ahrefTraffic: 16000,
    spamScore: 6,
    domainRating: 54,
    socialMediaPosting: false,
    sampleURL: "https://deltacasino.net/sample",
    costPrice: 750,
    costPriceValidFrom: new Date("2023-07-15"),
    costPriceValidTo: new Date("2024-07-15"),
    sellingPrice: 950,
    discount: 8,
    adultPrice: 100,
    casinoAdultPrice: 150,
    cbdPrice: 0,
    linkInsertionCost: 180,
    websiteRemark: "Popular casino site",
    webIP: "203.0.113.10",
    webCountry: "Malta",
    turnAroundTime: "24h",
    semrushTraffic: BigInt(60000),
    semrushFirstCountryName: "Malta",
    semrushSecondCountryName: "UK",
    semrushFirstCountryTraffic: 25000,
    semrushSecondCountryTraffic: 20000,
    semrushThirdCountryName: "Germany",
    semrushThirdCountryTraffic: 10000,
    semrushFourthCountryName: "Sweden",
    semrushFourthCountryTraffic: 4000,
    semrushFifthCountryName: "Norway",
    semrushFifthCountryTraffic: 2000,
    similarwebTraffic: 58000,
    siteUpdateDate: new Date("2024-03-15"),
    domainAuthorityUpdateDate: new Date("2024-03-15"),
    websiteType: "PR_NonBrand",
    language: "English",
    disclaimer: "Responsible gambling encouraged.",
    anchorText: false,
    bannerImagePrice: 300,
    costPriceUpdateDate: new Date("2024-02-01"),
    pureCategory: "Entertainment",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "AlmostPure",
    numberOfLinks: 100,
    semrushUpdateDate: new Date("2024-03-15"),
    semrushOrganicTraffic: 58000,
    semrushOrganicTrafficLastUpdated: new Date("2024-03-15"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 28,
    pocId: 2,
  },
  {
    id: 5,
    website: "epsiloncbd.com",
    niche: "CBD Products",
    contentCategories: "Health, Wellness",
    siteClassification: "Cbd",
    priceCategory: "Paid",
    domainAuthority: 47,
    pageAuthority: 43,
    linkAttribute: "NoFollow",
    ahrefTraffic: 8000,
    spamScore: 2,
    domainRating: 45,
    socialMediaPosting: true,
    sampleURL: "https://epsiloncbd.com/sample",
    costPrice: 600,
    costPriceValidFrom: new Date("2023-09-01"),
    costPriceValidTo: new Date("2024-09-01"),
    sellingPrice: 850,
    discount: 5,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 100,
    linkInsertionCost: 130,
    websiteRemark: "Wellness blog",
    webIP: "198.51.100.25",
    webCountry: "Canada",
    turnAroundTime: "36h",
    semrushTraffic: BigInt(40000),
    semrushFirstCountryName: "Canada",
    semrushSecondCountryName: "USA",
    semrushFirstCountryTraffic: 25000,
    semrushSecondCountryTraffic: 8000,
    semrushThirdCountryName: "UK",
    semrushThirdCountryTraffic: 3000,
    semrushFourthCountryName: "Australia",
    semrushFourthCountryTraffic: 2000,
    semrushFifthCountryName: "New Zealand",
    semrushFifthCountryTraffic: 1000,
    similarwebTraffic: 39000,
    siteUpdateDate: new Date("2024-04-05"),
    domainAuthorityUpdateDate: new Date("2024-04-05"),
    websiteType: "Language",
    language: "English",
    disclaimer: "CBD product information only.",
    anchorText: true,
    bannerImagePrice: 220,
    costPriceUpdateDate: new Date("2024-02-20"),
    pureCategory: "Health",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "Pure",
    numberOfLinks: 80,
    semrushUpdateDate: new Date("2024-04-05"),
    semrushOrganicTraffic: 39000,
    semrushOrganicTrafficLastUpdated: new Date("2024-04-05"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 6,
    pocId: 2,
  },

  {
    id: 6,
    website: "zetanews.org",
    niche: "News",
    contentCategories: "World, Politics",
    siteClassification: "Normal",
    priceCategory: "Paid",
    domainAuthority: 55,
    pageAuthority: 50,
    linkAttribute: "DoFollow",
    ahrefTraffic: 30000,
    spamScore: 4,
    domainRating: 58,
    socialMediaPosting: true,
    sampleURL: "https://zetanews.org/sample",
    costPrice: 700,
    costPriceValidFrom: new Date("2023-03-01"),
    costPriceValidTo: new Date("2024-03-01"),
    sellingPrice: 950,
    discount: 12,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 120,
    websiteRemark: "Reliable news source",
    webIP: "203.0.113.50",
    webCountry: "USA",
    turnAroundTime: "24h",
    semrushTraffic: BigInt(90000),
    semrushFirstCountryName: "USA",
    semrushSecondCountryName: "UK",
    semrushFirstCountryTraffic: 50000,
    semrushSecondCountryTraffic: 25000,
    semrushThirdCountryName: "Canada",
    semrushThirdCountryTraffic: 10000,
    semrushFourthCountryName: "Australia",
    semrushFourthCountryTraffic: 3000,
    semrushFifthCountryName: "India",
    semrushFifthCountryTraffic: 2000,
    similarwebTraffic: 88000,
    siteUpdateDate: new Date("2024-04-10"),
    domainAuthorityUpdateDate: new Date("2024-04-10"),
    websiteType: "PR",
    language: "English",
    disclaimer: "News content verified.",
    anchorText: true,
    bannerImagePrice: 300,
    costPriceUpdateDate: new Date("2024-01-05"),
    pureCategory: "Media",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "Pure",
    numberOfLinks: 130,
    semrushUpdateDate: new Date("2024-04-10"),
    semrushOrganicTraffic: 88000,
    semrushOrganicTrafficLastUpdated: new Date("2024-04-10"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 15,
    pocId: 2,
  },
  {
    id: 7,
    website: "omegasports.net",
    niche: "Sports",
    contentCategories: "Football, Basketball",
    siteClassification: "Normal",
    priceCategory: "Paid",
    domainAuthority: 40,
    pageAuthority: 35,
    linkAttribute: "NoFollow",
    ahrefTraffic: 15000,
    spamScore: 3,
    domainRating: 43,
    socialMediaPosting: false,
    sampleURL: "https://omegasports.net/sample",
    costPrice: 450,
    costPriceValidFrom: new Date("2023-06-15"),
    costPriceValidTo: new Date("2024-06-15"),
    sellingPrice: 600,
    discount: 5,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 90,
    websiteRemark: "Growing sports audience",
    webIP: "198.51.100.18",
    webCountry: "UK",
    turnAroundTime: "48h",
    semrushTraffic: BigInt(35000),
    semrushFirstCountryName: "UK",
    semrushSecondCountryName: "USA",
    semrushFirstCountryTraffic: 15000,
    semrushSecondCountryTraffic: 12000,
    semrushThirdCountryName: "Australia",
    semrushThirdCountryTraffic: 5000,
    semrushFourthCountryName: "Canada",
    semrushFourthCountryTraffic: 2000,
    semrushFifthCountryName: "Germany",
    semrushFifthCountryTraffic: 1000,
    similarwebTraffic: 34000,
    siteUpdateDate: new Date("2024-03-25"),
    domainAuthorityUpdateDate: new Date("2024-03-25"),
    websiteType: "Default",
    language: "English",
    disclaimer: "Sports content only.",
    anchorText: false,
    bannerImagePrice: 150,
    costPriceUpdateDate: new Date("2024-02-15"),
    pureCategory: "Sports",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "AlmostPure",
    numberOfLinks: 70,
    semrushUpdateDate: new Date("2024-03-25"),
    semrushOrganicTraffic: 34000,
    semrushOrganicTrafficLastUpdated: new Date("2024-03-25"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 22,
    pocId: 2,
  },
  {
    id: 8,
    website: "deltatravel.com",
    niche: "Travel",
    contentCategories: "Adventure, Tips",
    siteClassification: "Normal",
    priceCategory: "Exchange",
    domainAuthority: 48,
    pageAuthority: 44,
    linkAttribute: "DoFollow",
    ahrefTraffic: 20000,
    spamScore: 2,
    domainRating: 47,
    socialMediaPosting: true,
    sampleURL: "https://deltatravel.com/sample",
    costPrice: 650,
    costPriceValidFrom: new Date("2023-04-10"),
    costPriceValidTo: new Date("2024-04-10"),
    sellingPrice: 800,
    discount: 10,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 110,
    websiteRemark: "Great travel content",
    webIP: "192.0.2.25",
    webCountry: "Australia",
    turnAroundTime: "24h",
    semrushTraffic: BigInt(60000),
    semrushFirstCountryName: "Australia",
    semrushSecondCountryName: "New Zealand",
    semrushFirstCountryTraffic: 35000,
    semrushSecondCountryTraffic: 15000,
    semrushThirdCountryName: "USA",
    semrushThirdCountryTraffic: 8000,
    semrushFourthCountryName: "Canada",
    semrushFourthCountryTraffic: 4000,
    semrushFifthCountryName: "UK",
    semrushFifthCountryTraffic: 2000,
    similarwebTraffic: 59000,
    siteUpdateDate: new Date("2024-02-28"),
    domainAuthorityUpdateDate: new Date("2024-02-28"),
    websiteType: "PR_Brand",
    language: "English",
    disclaimer: "Travel advice only.",
    anchorText: true,
    bannerImagePrice: 200,
    costPriceUpdateDate: new Date("2024-01-20"),
    pureCategory: "Travel",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "Pure",
    numberOfLinks: 110,
    semrushUpdateDate: new Date("2024-02-28"),
    semrushOrganicTraffic: 59000,
    semrushOrganicTrafficLastUpdated: new Date("2024-02-28"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 8,
    pocId: 2,
  },
  {
    id: 9,
    website: "epsilonfinance.net",
    niche: "Finance",
    contentCategories: "Investing, Banking",
    siteClassification: "Organic",
    priceCategory: "Paid",
    domainAuthority: 62,
    pageAuthority: 59,
    linkAttribute: "Sponsored",
    ahrefTraffic: 30000,
    spamScore: 3,
    domainRating: 63,
    socialMediaPosting: true,
    sampleURL: "https://epsilonfinance.net/sample",
    costPrice: 1000,
    costPriceValidFrom: new Date("2023-02-20"),
    costPriceValidTo: new Date("2024-02-20"),
    sellingPrice: 1300,
    discount: 15,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 220,
    websiteRemark: "Trusted finance content",
    webIP: "203.0.113.30",
    webCountry: "Germany",
    turnAroundTime: "12h",
    semrushTraffic: BigInt(120000),
    semrushFirstCountryName: "Germany",
    semrushSecondCountryName: "France",
    semrushFirstCountryTraffic: 60000,
    semrushSecondCountryTraffic: 30000,
    semrushThirdCountryName: "UK",
    semrushThirdCountryTraffic: 15000,
    semrushFourthCountryName: "USA",
    semrushFourthCountryTraffic: 10000,
    semrushFifthCountryName: "Canada",
    semrushFifthCountryTraffic: 5000,
    similarwebTraffic: 115000,
    siteUpdateDate: new Date("2024-01-15"),
    domainAuthorityUpdateDate: new Date("2024-01-15"),
    websiteType: "PR",
    language: "English",
    disclaimer: "Financial advice disclaimer.",
    anchorText: true,
    bannerImagePrice: 400,
    costPriceUpdateDate: new Date("2024-01-01"),
    pureCategory: "Finance",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "Pure",
    numberOfLinks: 200,
    semrushUpdateDate: new Date("2024-01-15"),
    semrushOrganicTraffic: 115000,
    semrushOrganicTrafficLastUpdated: new Date("2024-01-15"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 9,
    pocId: 2,
  },
  {
    id: 10,
    website: "zetamedical.org",
    niche: "Medical",
    contentCategories: "Health, Wellness",
    siteClassification: "Normal",
    priceCategory: "Free",
    domainAuthority: 35,
    pageAuthority: 30,
    linkAttribute: "NoFollow",
    ahrefTraffic: 10000,
    spamScore: 2,
    domainRating: 38,
    socialMediaPosting: false,
    sampleURL: "https://zetamedical.org/sample",
    costPrice: 0,
    costPriceValidFrom: null,
    costPriceValidTo: null,
    sellingPrice: null,
    discount: null,
    adultPrice: 0,
    casinoAdultPrice: 0,
    cbdPrice: 0,
    linkInsertionCost: 0,
    websiteRemark: "Health resources",
    webIP: "192.0.2.55",
    webCountry: "India",
    turnAroundTime: "72h",
    semrushTraffic: BigInt(35000),
    semrushFirstCountryName: "India",
    semrushSecondCountryName: "USA",
    semrushFirstCountryTraffic: 20000,
    semrushSecondCountryTraffic: 8000,
    semrushThirdCountryName: "UK",
    semrushThirdCountryTraffic: 4000,
    semrushFourthCountryName: "Canada",
    semrushFourthCountryTraffic: 2000,
    semrushFifthCountryName: "Australia",
    semrushFifthCountryTraffic: 1000,
    similarwebTraffic: 34000,
    siteUpdateDate: new Date("2024-02-10"),
    domainAuthorityUpdateDate: new Date("2024-02-10"),
    websiteType: "Language",
    language: "English",
    disclaimer: "Medical advice disclaimer.",
    anchorText: false,
    bannerImagePrice: 0,
    costPriceUpdateDate: null,
    pureCategory: "Health",
    availability: true,
    isIndexed: true,
    websiteStatus: "Normal",
    websiteQuality: "AlmostPure",
    numberOfLinks: 60,
    semrushUpdateDate: new Date("2024-02-10"),
    semrushOrganicTraffic: 34000,
    semrushOrganicTrafficLastUpdated: new Date("2024-02-10"),
    createdAt: new Date(),
    updatedAt: new Date(),
    vendorId: 19,
    pocId: 2,
  },
  {
  id: 11,
  website: "kappamarketing.io",
  niche: "Marketing",
  contentCategories: "SEO, Content Strategy",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 50,
  pageAuthority: 45,
  linkAttribute: "DoFollow",
  ahrefTraffic: 22000,
  spamScore: 2,
  domainRating: 53,
  socialMediaPosting: true,
  sampleURL: "https://kappamarketing.io/sample",
  costPrice: 550,
  costPriceValidFrom: new Date("2023-08-01"),
  costPriceValidTo: new Date("2024-08-01"),
  sellingPrice: 700,
  discount: 8,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 110,
  websiteRemark: "SEO focused site",
  webIP: "198.51.100.100",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(75000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 40000,
  semrushSecondCountryTraffic: 20000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 10000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 5000,
  semrushFifthCountryName: "India",
  semrushFifthCountryTraffic: 3000,
  similarwebTraffic: 74000,
  siteUpdateDate: new Date("2024-03-28"),
  domainAuthorityUpdateDate: new Date("2024-03-28"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Marketing advice only.",
  anchorText: true,
  bannerImagePrice: 180,
  costPriceUpdateDate: new Date("2024-01-10"),
  pureCategory: "Marketing",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 105,
  semrushUpdateDate: new Date("2024-03-28"),
  semrushOrganicTraffic: 74000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-28"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 34,
  pocId: 2,
},
{
  id: 12,
  website: "lambdablog.net",
  niche: "Programming",
  contentCategories: "JavaScript, Python",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 42,
  pageAuthority: 38,
  linkAttribute: "NoFollow",
  ahrefTraffic: 13000,
  spamScore: 1,
  domainRating: 45,
  socialMediaPosting: false,
  sampleURL: "https://lambdablog.net/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Programming tutorials",
  webIP: "203.0.113.45",
  webCountry: "India",
  turnAroundTime: "72h",
  semrushTraffic: BigInt(37000),
  semrushFirstCountryName: "India",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 20000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 3000,
  semrushFourthCountryName: "Canada",
  semrushFourthCountryTraffic: 1500,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 500,
  similarwebTraffic: 36000,
  siteUpdateDate: new Date("2024-04-02"),
  domainAuthorityUpdateDate: new Date("2024-04-02"),
  websiteType: "Language",
  language: "English",
  disclaimer: "Educational content.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Education",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 60,
  semrushUpdateDate: new Date("2024-04-02"),
  semrushOrganicTraffic: 36000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-02"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 5,
  pocId: 2,
},
{
  id: 13,
  website: "omegadigital.com",
  niche: "Digital Marketing",
  contentCategories: "SEO, PPC",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 48,
  pageAuthority: 43,
  linkAttribute: "DoFollow",
  ahrefTraffic: 18000,
  spamScore: 3,
  domainRating: 50,
  socialMediaPosting: true,
  sampleURL: "https://omegadigital.com/sample",
  costPrice: 600,
  costPriceValidFrom: new Date("2023-07-01"),
  costPriceValidTo: new Date("2024-07-01"),
  sellingPrice: 750,
  discount: 7,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 100,
  websiteRemark: "Marketing agency site",
  webIP: "198.51.100.70",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(52000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 30000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 50000,
  siteUpdateDate: new Date("2024-03-15"),
  domainAuthorityUpdateDate: new Date("2024-03-15"),
  websiteType: "PR_Brand",
  language: "English",
  disclaimer: "Marketing insights.",
  anchorText: true,
  bannerImagePrice: 200,
  costPriceUpdateDate: new Date("2024-01-15"),
  pureCategory: "Marketing",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 95,
  semrushUpdateDate: new Date("2024-03-15"),
  semrushOrganicTraffic: 50000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-15"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 18,
  pocId: 2,
},
{
  id: 14,
  website: "thetadigital.org",
  niche: "Technology",
  contentCategories: "AI, Machine Learning",
  siteClassification: "Crypto",
  priceCategory: "Paid",
  domainAuthority: 57,
  pageAuthority: 52,
  linkAttribute: "Sponsored",
  ahrefTraffic: 28000,
  spamScore: 5,
  domainRating: 60,
  socialMediaPosting: true,
  sampleURL: "https://thetadigital.org/sample",
  costPrice: 850,
  costPriceValidFrom: new Date("2023-04-20"),
  costPriceValidTo: new Date("2024-04-20"),
  sellingPrice: 1100,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 180,
  websiteRemark: "Tech innovations blog",
  webIP: "172.217.11.22",
  webCountry: "USA",
  turnAroundTime: "12h",
  semrushTraffic: BigInt(80000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 40000,
  semrushSecondCountryTraffic: 25000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 8000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 78000,
  siteUpdateDate: new Date("2024-04-05"),
  domainAuthorityUpdateDate: new Date("2024-04-05"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Emerging tech news.",
  anchorText: true,
  bannerImagePrice: 350,
  costPriceUpdateDate: new Date("2024-02-01"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 125,
  semrushUpdateDate: new Date("2024-04-05"),
  semrushOrganicTraffic: 78000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-05"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 29,
  pocId: 2,
},
{
  id: 15,
  website: "omegafashion.com",
  niche: "Fashion",
  contentCategories: "Trends, Lifestyle",
  siteClassification: "Normal",
  priceCategory: "Exchange",
  domainAuthority: 43,
  pageAuthority: 39,
  linkAttribute: "DoFollow",
  ahrefTraffic: 14000,
  spamScore: 2,
  domainRating: 42,
  socialMediaPosting: false,
  sampleURL: "https://omegafashion.com/sample",
  costPrice: 500,
  costPriceValidFrom: new Date("2023-09-10"),
  costPriceValidTo: new Date("2024-09-10"),
  sellingPrice: 650,
  discount: 5,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 100,
  websiteRemark: "Fashion and lifestyle",
  webIP: "198.51.100.88",
  webCountry: "France",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(37000),
  semrushFirstCountryName: "France",
  semrushSecondCountryName: "Italy",
  semrushFirstCountryTraffic: 20000,
  semrushSecondCountryTraffic: 10000,
  semrushThirdCountryName: "Spain",
  semrushThirdCountryTraffic: 5000,
  semrushFourthCountryName: "UK",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "USA",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 36000,
  siteUpdateDate: new Date("2024-03-18"),
  domainAuthorityUpdateDate: new Date("2024-03-18"),
  websiteType: "Default",
  language: "English",
  disclaimer: "Fashion content only.",
  anchorText: false,
  bannerImagePrice: 150,
  costPriceUpdateDate: new Date("2024-01-20"),
  pureCategory: "Lifestyle",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 80,
  semrushUpdateDate: new Date("2024-03-18"),
  semrushOrganicTraffic: 36000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-18"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 31,
  pocId: 2,
},
{
  id: 16,
  website: "zetatechhub.com",
  niche: "Tech Reviews",
  contentCategories: "Gadgets, Software",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 46,
  pageAuthority: 41,
  linkAttribute: "DoFollow",
  ahrefTraffic: 19000,
  spamScore: 3,
  domainRating: 48,
  socialMediaPosting: true,
  sampleURL: "https://zetatechhub.com/sample",
  costPrice: 620,
  costPriceValidFrom: new Date("2023-06-20"),
  costPriceValidTo: new Date("2024-06-20"),
  sellingPrice: 800,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 120,
  websiteRemark: "Tech gadget reviews",
  webIP: "172.217.11.30",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(55000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 30000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 6000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 2500,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 53000,
  siteUpdateDate: new Date("2024-04-01"),
  domainAuthorityUpdateDate: new Date("2024-04-01"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Reviews are opinions.",
  anchorText: true,
  bannerImagePrice: 210,
  costPriceUpdateDate: new Date("2024-02-10"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 100,
  semrushUpdateDate: new Date("2024-04-01"),
  semrushOrganicTraffic: 53000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 4,
  pocId: 2,
},
{
  id: 17,
  website: "alphamedia.net",
  niche: "Media",
  contentCategories: "News, Analysis",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 37,
  pageAuthority: 33,
  linkAttribute: "NoFollow",
  ahrefTraffic: 11000,
  spamScore: 2,
  domainRating: 39,
  socialMediaPosting: false,
  sampleURL: "https://alphamedia.net/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Independent media outlet",
  webIP: "198.51.100.105",
  webCountry: "USA",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(38000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 18000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "India",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 37000,
  siteUpdateDate: new Date("2024-03-20"),
  domainAuthorityUpdateDate: new Date("2024-03-20"),
  websiteType: "PR_NonBrand",
  language: "English",
  disclaimer: "Editorial content.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 65,
  semrushUpdateDate: new Date("2024-03-20"),
  semrushOrganicTraffic: 37000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-20"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 13,
  pocId: 2,
},
{
  id: 18,
  website: "betacrypto.io",
  niche: "Cryptocurrency",
  contentCategories: "News, Trading",
  siteClassification: "Crypto",
  priceCategory: "Paid",
  domainAuthority: 59,
  pageAuthority: 54,
  linkAttribute: "Sponsored",
  ahrefTraffic: 27000,
  spamScore: 6,
  domainRating: 62,
  socialMediaPosting: true,
  sampleURL: "https://betacrypto.io/sample",
  costPrice: 870,
  costPriceValidFrom: new Date("2023-05-10"),
  costPriceValidTo: new Date("2024-05-10"),
  sellingPrice: 1100,
  discount: 12,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 190,
  websiteRemark: "Crypto market updates",
  webIP: "172.217.11.35",
  webCountry: "USA",
  turnAroundTime: "18h",
  semrushTraffic: BigInt(75000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 40000,
  semrushSecondCountryTraffic: 25000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 7000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 73000,
  siteUpdateDate: new Date("2024-04-05"),
  domainAuthorityUpdateDate: new Date("2024-04-05"),
  websiteType: "PR_Brand",
  language: "English",
  disclaimer: "Crypto trading disclaimer.",
  anchorText: true,
  bannerImagePrice: 320,
  costPriceUpdateDate: new Date("2024-02-15"),
  pureCategory: "Finance",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 140,
  semrushUpdateDate: new Date("2024-04-05"),
  semrushOrganicTraffic: 73000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-05"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 10,
  pocId: 2,
},
{
  id: 19,
  website: "alphacannabis.com",
  niche: "CBD",
  contentCategories: "Products, Health",
  siteClassification: "Cbd",
  priceCategory: "Paid",
  domainAuthority: 49,
  pageAuthority: 44,
  linkAttribute: "NoFollow",
  ahrefTraffic: 14000,
  spamScore: 3,
  domainRating: 47,
  socialMediaPosting: false,
  sampleURL: "https://alphacannabis.com/sample",
  costPrice: 620,
  costPriceValidFrom: new Date("2023-08-10"),
  costPriceValidTo: new Date("2024-08-10"),
  sellingPrice: 800,
  discount: 7,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 120,
  linkInsertionCost: 130,
  websiteRemark: "CBD product info",
  webIP: "198.51.100.90",
  webCountry: "Canada",
  turnAroundTime: "36h",
  semrushTraffic: BigInt(39000),
  semrushFirstCountryName: "Canada",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 22000,
  semrushSecondCountryTraffic: 11000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 38000,
  siteUpdateDate: new Date("2024-03-30"),
  domainAuthorityUpdateDate: new Date("2024-03-30"),
  websiteType: "Language",
  language: "English",
  disclaimer: "CBD info disclaimer.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: new Date("2024-01-25"),
  pureCategory: "Health",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 75,
  semrushUpdateDate: new Date("2024-03-30"),
  semrushOrganicTraffic: 38000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-30"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 26,
  pocId: 2,
},
{
  id: 20,
  website: "omegasoftwaresolutions.com",
  niche: "Software",
  contentCategories: "Development, Testing",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 54,
  pageAuthority: 49,
  linkAttribute: "DoFollow",
  ahrefTraffic: 26000,
  spamScore: 3,
  domainRating: 57,
  socialMediaPosting: true,
  sampleURL: "https://omegasoftwaresolutions.com/sample",
  costPrice: 800,
  costPriceValidFrom: new Date("2023-05-15"),
  costPriceValidTo: new Date("2024-05-15"),
  sellingPrice: 1050,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 140,
  websiteRemark: "Custom software development",
  webIP: "203.0.113.55",
  webCountry: "UK",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(90000),
  semrushFirstCountryName: "UK",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 45000,
  semrushSecondCountryTraffic: 30000,
  semrushThirdCountryName: "Canada",
  semrushThirdCountryTraffic: 10000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 2000,
  similarwebTraffic: 88000,
  siteUpdateDate: new Date("2024-04-10"),
  domainAuthorityUpdateDate: new Date("2024-04-10"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Software solutions provider.",
  anchorText: true,
  bannerImagePrice: 260,
  costPriceUpdateDate: new Date("2024-02-05"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 140,
  semrushUpdateDate: new Date("2024-04-10"),
  semrushOrganicTraffic: 88000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-10"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 1,
  pocId: 2,
},
{
  id: 21,
  website: "zetablogs.com",
  niche: "Blogging",
  contentCategories: "Personal, Lifestyle",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 38,
  pageAuthority: 33,
  linkAttribute: "NoFollow",
  ahrefTraffic: 12000,
  spamScore: 2,
  domainRating: 40,
  socialMediaPosting: false,
  sampleURL: "https://zetablogs.com/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Personal blogging platform",
  webIP: "192.168.0.25",
  webCountry: "USA",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(28000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 15000,
  semrushSecondCountryTraffic: 8000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 3000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 27000,
  siteUpdateDate: new Date("2024-03-10"),
  domainAuthorityUpdateDate: new Date("2024-03-10"),
  websiteType: "Default",
  language: "English",
  disclaimer: "Personal opinions only.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Lifestyle",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 50,
  semrushUpdateDate: new Date("2024-03-10"),
  semrushOrganicTraffic: 27000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-10"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 7,
  pocId: 2,
},
{
  id: 22,
  website: "omegadigitalmedia.com",
  niche: "Digital Media",
  contentCategories: "Video, Podcast",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 52,
  pageAuthority: 48,
  linkAttribute: "DoFollow",
  ahrefTraffic: 21000,
  spamScore: 3,
  domainRating: 55,
  socialMediaPosting: true,
  sampleURL: "https://omegadigitalmedia.com/sample",
  costPrice: 700,
  costPriceValidFrom: new Date("2023-09-01"),
  costPriceValidTo: new Date("2024-09-01"),
  sellingPrice: 900,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 130,
  websiteRemark: "Video and audio content",
  webIP: "203.0.113.90",
  webCountry: "UK",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(65000),
  semrushFirstCountryName: "UK",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 35000,
  semrushSecondCountryTraffic: 20000,
  semrushThirdCountryName: "Canada",
  semrushThirdCountryTraffic: 6000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "India",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 64000,
  siteUpdateDate: new Date("2024-02-25"),
  domainAuthorityUpdateDate: new Date("2024-02-25"),
  websiteType: "PR_Brand",
  language: "English",
  disclaimer: "Media rights reserved.",
  anchorText: true,
  bannerImagePrice: 280,
  costPriceUpdateDate: new Date("2024-01-15"),
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 110,
  semrushUpdateDate: new Date("2024-02-25"),
  semrushOrganicTraffic: 64000,
  semrushOrganicTrafficLastUpdated: new Date("2024-02-25"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 12,
  pocId: 2,
},
{
  id: 23,
  website: "sigmatechnologies.io",
  niche: "Technology",
  contentCategories: "Software, Hardware",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 58,
  pageAuthority: 53,
  linkAttribute: "Sponsored",
  ahrefTraffic: 27000,
  spamScore: 4,
  domainRating: 60,
  socialMediaPosting: true,
  sampleURL: "https://sigmatechnologies.io/sample",
  costPrice: 850,
  costPriceValidFrom: new Date("2023-05-15"),
  costPriceValidTo: new Date("2024-05-15"),
  sellingPrice: 1100,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 160,
  websiteRemark: "Tech industry leader",
  webIP: "172.217.11.45",
  webCountry: "USA",
  turnAroundTime: "12h",
  semrushTraffic: BigInt(80000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 42000,
  semrushSecondCountryTraffic: 25000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 7000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 4000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 2000,
  similarwebTraffic: 78000,
  siteUpdateDate: new Date("2024-03-30"),
  domainAuthorityUpdateDate: new Date("2024-03-30"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Technology insights.",
  anchorText: true,
  bannerImagePrice: 350,
  costPriceUpdateDate: new Date("2024-02-20"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 130,
  semrushUpdateDate: new Date("2024-03-30"),
  semrushOrganicTraffic: 78000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-30"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 17,
  pocId: 2,
},
{
  id: 24,
  website: "omegafitness.org",
  niche: "Fitness",
  contentCategories: "Workouts, Nutrition",
  siteClassification: "Normal",
  priceCategory: "Exchange",
  domainAuthority: 44,
  pageAuthority: 40,
  linkAttribute: "DoFollow",
  ahrefTraffic: 17000,
  spamScore: 3,
  domainRating: 46,
  socialMediaPosting: true,
  sampleURL: "https://omegafitness.org/sample",
  costPrice: 580,
  costPriceValidFrom: new Date("2023-07-10"),
  costPriceValidTo: new Date("2024-07-10"),
  sellingPrice: 750,
  discount: 7,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 120,
  websiteRemark: "Health and fitness blog",
  webIP: "198.51.100.115",
  webCountry: "Canada",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(43000),
  semrushFirstCountryName: "Canada",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 25000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 42000,
  siteUpdateDate: new Date("2024-03-22"),
  domainAuthorityUpdateDate: new Date("2024-03-22"),
  websiteType: "PR_NonBrand",
  language: "English",
  disclaimer: "Health tips and guides.",
  anchorText: true,
  bannerImagePrice: 200,
  costPriceUpdateDate: new Date("2024-01-30"),
  pureCategory: "Health",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 85,
  semrushUpdateDate: new Date("2024-03-22"),
  semrushOrganicTraffic: 42000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-22"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 20,
  pocId: 2,
},
{
  id: 25,
  website: "zetahome.com",
  niche: "Home Improvement",
  contentCategories: "DIY, Gardening",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 41,
  pageAuthority: 37,
  linkAttribute: "DoFollow",
  ahrefTraffic: 16000,
  spamScore: 2,
  domainRating: 43,
  socialMediaPosting: false,
  sampleURL: "https://zetahome.com/sample",
  costPrice: 520,
  costPriceValidFrom: new Date("2023-10-01"),
  costPriceValidTo: new Date("2024-10-01"),
  sellingPrice: 670,
  discount: 6,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 110,
  websiteRemark: "Home and garden tips",
  webIP: "203.0.113.120",
  webCountry: "USA",
  turnAroundTime: "36h",
  semrushTraffic: BigInt(40000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 22000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 3500,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1500,
  similarwebTraffic: 39000,
  siteUpdateDate: new Date("2024-04-01"),
  domainAuthorityUpdateDate: new Date("2024-04-01"),
  websiteType: "Default",
  language: "English",
  disclaimer: "Home improvement content.",
  anchorText: false,
  bannerImagePrice: 180,
  costPriceUpdateDate: new Date("2024-02-10"),
  pureCategory: "Lifestyle",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 75,
  semrushUpdateDate: new Date("2024-04-01"),
  semrushOrganicTraffic: 39000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 14,
  pocId: 2,
},
{
  id: 26,
  website: "alphasportsonline.net",
  niche: "Sports",
  contentCategories: "Football, Baseball",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 45,
  pageAuthority: 41,
  linkAttribute: "DoFollow",
  ahrefTraffic: 21000,
  spamScore: 3,
  domainRating: 48,
  socialMediaPosting: true,
  sampleURL: "https://alphasportsonline.net/sample",
  costPrice: 630,
  costPriceValidFrom: new Date("2023-07-05"),
  costPriceValidTo: new Date("2024-07-05"),
  sellingPrice: 800,
  discount: 9,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 120,
  websiteRemark: "Sports news and analysis",
  webIP: "198.51.100.130",
  webCountry: "UK",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(55000),
  semrushFirstCountryName: "UK",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 30000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "Canada",
  semrushThirdCountryTraffic: 5000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2500,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 54000,
  siteUpdateDate: new Date("2024-02-15"),
  domainAuthorityUpdateDate: new Date("2024-02-15"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Sports content only.",
  anchorText: true,
  bannerImagePrice: 210,
  costPriceUpdateDate: new Date("2024-01-25"),
  pureCategory: "Sports",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 100,
  semrushUpdateDate: new Date("2024-02-15"),
  semrushOrganicTraffic: 54000,
  semrushOrganicTrafficLastUpdated: new Date("2024-02-15"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 24,
  pocId: 2,
},
{
  id: 27,
  website: "betanewsmedia.com",
  niche: "News",
  contentCategories: "Local, Politics",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 36,
  pageAuthority: 31,
  linkAttribute: "NoFollow",
  ahrefTraffic: 13000,
  spamScore: 2,
  domainRating: 39,
  socialMediaPosting: false,
  sampleURL: "https://betanewsmedia.com/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Local news portal",
  webIP: "192.168.0.75",
  webCountry: "USA",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(28000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 16000,
  semrushSecondCountryTraffic: 9000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 2000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 1500,
  semrushFifthCountryName: "India",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 27000,
  siteUpdateDate: new Date("2024-03-12"),
  domainAuthorityUpdateDate: new Date("2024-03-12"),
  websiteType: "Default",
  language: "English",
  disclaimer: "News content only.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 55,
  semrushUpdateDate: new Date("2024-03-12"),
  semrushOrganicTraffic: 27000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-12"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 16,
  pocId: 2,
},
{
  id: 28,
  website: "omegatechworld.net",
  niche: "Tech",
  contentCategories: "Gadgets, Reviews",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 53,
  pageAuthority: 49,
  linkAttribute: "DoFollow",
  ahrefTraffic: 23000,
  spamScore: 3,
  domainRating: 56,
  socialMediaPosting: true,
  sampleURL: "https://omegatechworld.net/sample",
  costPrice: 710,
  costPriceValidFrom: new Date("2023-08-20"),
  costPriceValidTo: new Date("2024-08-20"),
  sellingPrice: 900,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 140,
  websiteRemark: "Tech reviews and news",
  webIP: "203.0.113.150",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(72000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 37000,
  semrushSecondCountryTraffic: 22000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 7000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 71000,
  siteUpdateDate: new Date("2024-03-22"),
  domainAuthorityUpdateDate: new Date("2024-03-22"),
  websiteType: "PR_Brand",
  language: "English",
  disclaimer: "Tech news and reviews.",
  anchorText: true,
  bannerImagePrice: 230,
  costPriceUpdateDate: new Date("2024-02-01"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 115,
  semrushUpdateDate: new Date("2024-03-22"),
  semrushOrganicTraffic: 71000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-22"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 27,
  pocId: 2,
},
{
  id: 29,
  website: "sigmamediahub.com",
  niche: "Media",
  contentCategories: "News, Entertainment",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 47,
  pageAuthority: 43,
  linkAttribute: "DoFollow",
  ahrefTraffic: 19000,
  spamScore: 3,
  domainRating: 48,
  socialMediaPosting: true,
  sampleURL: "https://sigmamediahub.com/sample",
  costPrice: 600,
  costPriceValidFrom: new Date("2023-06-25"),
  costPriceValidTo: new Date("2024-06-25"),
  sellingPrice: 750,
  discount: 8,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 110,
  websiteRemark: "Media and news portal",
  webIP: "198.51.100.140",
  webCountry: "Canada",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(47000),
  semrushFirstCountryName: "Canada",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 25000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 46000,
  siteUpdateDate: new Date("2024-03-18"),
  domainAuthorityUpdateDate: new Date("2024-03-18"),
  websiteType: "PR_NonBrand",
  language: "English",
  disclaimer: "Entertainment and news.",
  anchorText: true,
  bannerImagePrice: 200,
  costPriceUpdateDate: new Date("2024-01-28"),
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 90,
  semrushUpdateDate: new Date("2024-03-18"),
  semrushOrganicTraffic: 46000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-18"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 21,
  pocId: 2,
},
{
  id: 30,
  website: "alphaproductions.net",
  niche: "Entertainment",
  contentCategories: "Movies, Music",
  siteClassification: "Normal",
  priceCategory: "Exchange",
  domainAuthority: 44,
  pageAuthority: 40,
  linkAttribute: "DoFollow",
  ahrefTraffic: 17000,
  spamScore: 2,
  domainRating: 45,
  socialMediaPosting: true,
  sampleURL: "https://alphaproductions.net/sample",
  costPrice: 550,
  costPriceValidFrom: new Date("2023-08-05"),
  costPriceValidTo: new Date("2024-08-05"),
  sellingPrice: 700,
  discount: 7,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 115,
  websiteRemark: "Entertainment news and reviews",
  webIP: "203.0.113.160",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(42000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 23000,
  semrushSecondCountryTraffic: 11000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 41000,
  siteUpdateDate: new Date("2024-03-25"),
  domainAuthorityUpdateDate: new Date("2024-03-25"),
  websiteType: "Default",
  language: "English",
  disclaimer: "Entertainment content only.",
  anchorText: true,
  bannerImagePrice: 180,
  costPriceUpdateDate: new Date("2024-02-12"),
  pureCategory: "Entertainment",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 85,
  semrushUpdateDate: new Date("2024-03-25"),
  semrushOrganicTraffic: 41000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-25"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 11,
  pocId: 2,
},{
  id: 31,
  website: "betasoftwaresolutions.com",
  niche: "Software",
  contentCategories: "Development, AI",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 56,
  pageAuthority: 52,
  linkAttribute: "DoFollow",
  ahrefTraffic: 28000,
  spamScore: 3,
  domainRating: 58,
  socialMediaPosting: true,
  sampleURL: "https://betasoftwaresolutions.com/sample",
  costPrice: 720,
  costPriceValidFrom: new Date("2023-07-10"),
  costPriceValidTo: new Date("2024-07-10"),
  sellingPrice: 900,
  discount: 12,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 140,
  websiteRemark: "AI-focused software services",
  webIP: "198.51.100.120",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(85000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 45000,
  semrushSecondCountryTraffic: 25000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 8000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 4000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 2000,
  similarwebTraffic: 83000,
  siteUpdateDate: new Date("2024-04-01"),
  domainAuthorityUpdateDate: new Date("2024-04-01"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Innovative software solutions.",
  anchorText: true,
  bannerImagePrice: 300,
  costPriceUpdateDate: new Date("2024-02-15"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 140,
  semrushUpdateDate: new Date("2024-04-01"),
  semrushOrganicTraffic: 83000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 33,
  pocId: 2,
},
{
  id: 32,
  website: "sigmatechblog.net",
  niche: "Tech Blog",
  contentCategories: "Programming, Gadgets",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 43,
  pageAuthority: 39,
  linkAttribute: "NoFollow",
  ahrefTraffic: 15000,
  spamScore: 2,
  domainRating: 45,
  socialMediaPosting: false,
  sampleURL: "https://sigmatechblog.net/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Tech tutorials and reviews",
  webIP: "203.0.113.130",
  webCountry: "India",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(40000),
  semrushFirstCountryName: "India",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 20000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 3000,
  semrushFourthCountryName: "Canada",
  semrushFourthCountryTraffic: 1000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 39000,
  siteUpdateDate: new Date("2024-03-28"),
  domainAuthorityUpdateDate: new Date("2024-03-28"),
  websiteType: "Language",
  language: "English",
  disclaimer: "Educational content.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Education",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 70,
  semrushUpdateDate: new Date("2024-03-28"),
  semrushOrganicTraffic: 39000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-28"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 36,
  pocId: 2,
},
{
  id: 33,
  website: "omegafinancegroup.com",
  niche: "Finance",
  contentCategories: "Investing, Banking",
  siteClassification: "Organic",
  priceCategory: "Paid",
  domainAuthority: 60,
  pageAuthority: 55,
  linkAttribute: "Sponsored",
  ahrefTraffic: 31000,
  spamScore: 4,
  domainRating: 62,
  socialMediaPosting: true,
  sampleURL: "https://omegafinancegroup.com/sample",
  costPrice: 900,
  costPriceValidFrom: new Date("2023-05-05"),
  costPriceValidTo: new Date("2024-05-05"),
  sellingPrice: 1200,
  discount: 15,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 200,
  websiteRemark: "Trusted finance advice",
  webIP: "198.51.100.140",
  webCountry: "Germany",
  turnAroundTime: "12h",
  semrushTraffic: BigInt(110000),
  semrushFirstCountryName: "Germany",
  semrushSecondCountryName: "France",
  semrushFirstCountryTraffic: 55000,
  semrushSecondCountryTraffic: 30000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 15000,
  semrushFourthCountryName: "USA",
  semrushFourthCountryTraffic: 10000,
  semrushFifthCountryName: "Canada",
  semrushFifthCountryTraffic: 5000,
  similarwebTraffic: 105000,
  siteUpdateDate: new Date("2024-04-05"),
  domainAuthorityUpdateDate: new Date("2024-04-05"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Finance tips and news.",
  anchorText: true,
  bannerImagePrice: 400,
  costPriceUpdateDate: new Date("2024-02-10"),
  pureCategory: "Finance",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 180,
  semrushUpdateDate: new Date("2024-04-05"),
  semrushOrganicTraffic: 105000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-05"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 25,
  pocId: 2,
},
{
  id: 34,
  website: "zetamedicine.org",
  niche: "Medical",
  contentCategories: "Health, Wellness",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 35,
  pageAuthority: 30,
  linkAttribute: "NoFollow",
  ahrefTraffic: 11000,
  spamScore: 2,
  domainRating: 38,
  socialMediaPosting: false,
  sampleURL: "https://zetamedicine.org/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Health resources and advice",
  webIP: "192.0.2.60",
  webCountry: "India",
  turnAroundTime: "72h",
  semrushTraffic: BigInt(36000),
  semrushFirstCountryName: "India",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 21000,
  semrushSecondCountryTraffic: 9000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Canada",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 35000,
  siteUpdateDate: new Date("2024-03-15"),
  domainAuthorityUpdateDate: new Date("2024-03-15"),
  websiteType: "Language",
  language: "English",
  disclaimer: "Medical advice disclaimer.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Health",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 65,
  semrushUpdateDate: new Date("2024-03-15"),
  semrushOrganicTraffic: 35000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-15"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 22,
  pocId: 2,
},
{
  id: 35,
  website: "omegatravelers.com",
  niche: "Travel",
  contentCategories: "Tips, Reviews",
  siteClassification: "Normal",
  priceCategory: "Exchange",
  domainAuthority: 46,
  pageAuthority: 42,
  linkAttribute: "DoFollow",
  ahrefTraffic: 19000,
  spamScore: 3,
  domainRating: 48,
  socialMediaPosting: true,
  sampleURL: "https://omegatravelers.com/sample",
  costPrice: 600,
  costPriceValidFrom: new Date("2023-06-05"),
  costPriceValidTo: new Date("2024-06-05"),
  sellingPrice: 780,
  discount: 8,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 130,
  websiteRemark: "Travel guides and tips",
  webIP: "203.0.113.80",
  webCountry: "Australia",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(47000),
  semrushFirstCountryName: "Australia",
  semrushSecondCountryName: "New Zealand",
  semrushFirstCountryTraffic: 25000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "USA",
  semrushThirdCountryTraffic: 6000,
  semrushFourthCountryName: "Canada",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "UK",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 46000,
  siteUpdateDate: new Date("2024-03-20"),
  domainAuthorityUpdateDate: new Date("2024-03-20"),
  websiteType: "PR_NonBrand",
  language: "English",
  disclaimer: "Travel advice and reviews.",
  anchorText: true,
  bannerImagePrice: 210,
  costPriceUpdateDate: new Date("2024-01-30"),
  pureCategory: "Travel",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 90,
  semrushUpdateDate: new Date("2024-03-20"),
  semrushOrganicTraffic: 46000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-20"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 30,
  pocId: 2,
},
{
  id: 36,
  website: "alphamarketinggroup.com",
  niche: "Marketing",
  contentCategories: "SEO, Social Media",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 50,
  pageAuthority: 45,
  linkAttribute: "DoFollow",
  ahrefTraffic: 24000,
  spamScore: 3,
  domainRating: 53,
  socialMediaPosting: true,
  sampleURL: "https://alphamarketinggroup.com/sample",
  costPrice: 650,
  costPriceValidFrom: new Date("2023-08-10"),
  costPriceValidTo: new Date("2024-08-10"),
  sellingPrice: 850,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 140,
  websiteRemark: "Digital marketing agency",
  webIP: "198.51.100.135",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(78000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 42000,
  semrushSecondCountryTraffic: 22000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 7000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2500,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1500,
  similarwebTraffic: 76000,
  siteUpdateDate: new Date("2024-04-01"),
  domainAuthorityUpdateDate: new Date("2024-04-01"),
  websiteType: "PR_Brand",
  language: "English",
  disclaimer: "Marketing strategies and tips.",
  anchorText: true,
  bannerImagePrice: 250,
  costPriceUpdateDate: new Date("2024-02-10"),
  pureCategory: "Marketing",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 120,
  semrushUpdateDate: new Date("2024-04-01"),
  semrushOrganicTraffic: 76000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 32,
  pocId: 2,
},
{
  id: 37,
  website: "betatechnologies.net",
  niche: "Technology",
  contentCategories: "Cloud, Software",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 55,
  pageAuthority: 51,
  linkAttribute: "DoFollow",
  ahrefTraffic: 29000,
  spamScore: 3,
  domainRating: 57,
  socialMediaPosting: true,
  sampleURL: "https://betatechnologies.net/sample",
  costPrice: 750,
  costPriceValidFrom: new Date("2023-06-20"),
  costPriceValidTo: new Date("2024-06-20"),
  sellingPrice: 950,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 150,
  websiteRemark: "Cloud computing news",
  webIP: "172.217.11.40",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(87000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 45000,
  semrushSecondCountryTraffic: 25000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 9000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 3500,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 1500,
  similarwebTraffic: 85000,
  siteUpdateDate: new Date("2024-03-30"),
  domainAuthorityUpdateDate: new Date("2024-03-30"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Tech industry updates.",
  anchorText: true,
  bannerImagePrice: 300,
  costPriceUpdateDate: new Date("2024-02-15"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 130,
  semrushUpdateDate: new Date("2024-03-30"),
  semrushOrganicTraffic: 85000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-30"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 23,
  pocId: 2,
},
{
  id: 38,
  website: "omegamedianetwork.com",
  niche: "Media",
  contentCategories: "TV, Radio",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 39,
  pageAuthority: 34,
  linkAttribute: "NoFollow",
  ahrefTraffic: 14000,
  spamScore: 2,
  domainRating: 41,
  socialMediaPosting: false,
  sampleURL: "https://omegamedianetwork.com/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Media streaming site",
  webIP: "198.51.100.150",
  webCountry: "UK",
  turnAroundTime: "72h",
  semrushTraffic: BigInt(39000),
  semrushFirstCountryName: "UK",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 18000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "Canada",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 38000,
  siteUpdateDate: new Date("2024-03-18"),
  domainAuthorityUpdateDate: new Date("2024-03-18"),
  websiteType: "Language",
  language: "English",
  disclaimer: "Streaming services.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 75,
  semrushUpdateDate: new Date("2024-03-18"),
  semrushOrganicTraffic: 38000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-18"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 9,
  pocId: 2,
},
{
  id: 39,
  website: "alphahomeimprovement.com",
  niche: "Home",
  contentCategories: "DIY, Renovation",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 42,
  pageAuthority: 38,
  linkAttribute: "DoFollow",
  ahrefTraffic: 17000,
  spamScore: 3,
  domainRating: 45,
  socialMediaPosting: true,
  sampleURL: "https://alphahomeimprovement.com/sample",
  costPrice: 550,
  costPriceValidFrom: new Date("2023-09-10"),
  costPriceValidTo: new Date("2024-09-10"),
  sellingPrice: 700,
  discount: 6,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 120,
  websiteRemark: "Home improvement tips",
  webIP: "203.0.113.165",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(42000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 22000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 3500,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1500,
  similarwebTraffic: 41000,
  siteUpdateDate: new Date("2024-03-25"),
  domainAuthorityUpdateDate: new Date("2024-03-25"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Home renovation advice.",
  anchorText: true,
  bannerImagePrice: 180,
  costPriceUpdateDate: new Date("2024-02-12"),
  pureCategory: "Lifestyle",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 85,
  semrushUpdateDate: new Date("2024-03-25"),
  semrushOrganicTraffic: 41000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-25"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 20,
  pocId: 2,
},
{
  id: 40,
  website: "betacannabis.com",
  niche: "CBD",
  contentCategories: "Health, Products",
  siteClassification: "Cbd",
  priceCategory: "Paid",
  domainAuthority: 48,
  pageAuthority: 43,
  linkAttribute: "NoFollow",
  ahrefTraffic: 15000,
  spamScore: 3,
  domainRating: 46,
  socialMediaPosting: false,
  sampleURL: "https://betacannabis.com/sample",
  costPrice: 600,
  costPriceValidFrom: new Date("2023-08-20"),
  costPriceValidTo: new Date("2024-08-20"),
  sellingPrice: 800,
  discount: 7,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 130,
  linkInsertionCost: 130,
  websiteRemark: "CBD info and products",
  webIP: "198.51.100.175",
  webCountry: "Canada",
  turnAroundTime: "36h",
  semrushTraffic: BigInt(40000),
  semrushFirstCountryName: "Canada",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 22000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 39000,
  siteUpdateDate: new Date("2024-03-28"),
  domainAuthorityUpdateDate: new Date("2024-03-28"),
  websiteType: "Language",
  language: "English",
  disclaimer: "CBD health information.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: new Date("2024-01-28"),
  pureCategory: "Health",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 80,
  semrushUpdateDate: new Date("2024-03-28"),
  semrushOrganicTraffic: 39000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-28"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 26,
  pocId: 2,
},{
  id: 41,
  website: "omegafitnesshub.com",
  niche: "Fitness",
  contentCategories: "Workouts, Nutrition",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 47,
  pageAuthority: 43,
  linkAttribute: "DoFollow",
  ahrefTraffic: 20000,
  spamScore: 3,
  domainRating: 49,
  socialMediaPosting: true,
  sampleURL: "https://omegafitnesshub.com/sample",
  costPrice: 650,
  costPriceValidFrom: new Date("2023-07-15"),
  costPriceValidTo: new Date("2024-07-15"),
  sellingPrice: 850,
  discount: 8,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 130,
  websiteRemark: "Fitness tips and guides",
  webIP: "198.51.100.185",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(47000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 26000,
  semrushSecondCountryTraffic: 14000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 46000,
  siteUpdateDate: new Date("2024-04-05"),
  domainAuthorityUpdateDate: new Date("2024-04-05"),
  websiteType: "PR_NonBrand",
  language: "English",
  disclaimer: "Fitness and health advice.",
  anchorText: true,
  bannerImagePrice: 220,
  costPriceUpdateDate: new Date("2024-02-10"),
  pureCategory: "Health",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 90,
  semrushUpdateDate: new Date("2024-04-05"),
  semrushOrganicTraffic: 46000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-05"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 30,
  pocId: 2,
},
{
  id: 42,
  website: "zetatechnologynews.com",
  niche: "Technology",
  contentCategories: "News, Reviews",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 55,
  pageAuthority: 50,
  linkAttribute: "DoFollow",
  ahrefTraffic: 29000,
  spamScore: 3,
  domainRating: 56,
  socialMediaPosting: true,
  sampleURL: "https://zetatechnologynews.com/sample",
  costPrice: 750,
  costPriceValidFrom: new Date("2023-06-15"),
  costPriceValidTo: new Date("2024-06-15"),
  sellingPrice: 950,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 150,
  websiteRemark: "Latest tech news",
  webIP: "172.217.11.50",
  webCountry: "USA",
  turnAroundTime: "12h",
  semrushTraffic: BigInt(82000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 43000,
  semrushSecondCountryTraffic: 27000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 7000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 2000,
  similarwebTraffic: 80000,
  siteUpdateDate: new Date("2024-04-01"),
  domainAuthorityUpdateDate: new Date("2024-04-01"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Tech news and updates.",
  anchorText: true,
  bannerImagePrice: 280,
  costPriceUpdateDate: new Date("2024-02-20"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 125,
  semrushUpdateDate: new Date("2024-04-01"),
  semrushOrganicTraffic: 80000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 34,
  pocId: 2,
},
{
  id: 43,
  website: "omeganewsnetwork.com",
  niche: "News",
  contentCategories: "World, Politics",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 38,
  pageAuthority: 33,
  linkAttribute: "NoFollow",
  ahrefTraffic: 15000,
  spamScore: 2,
  domainRating: 40,
  socialMediaPosting: false,
  sampleURL: "https://omeganewsnetwork.com/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Global news portal",
  webIP: "198.51.100.195",
  webCountry: "UK",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(32000),
  semrushFirstCountryName: "UK",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 18000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "Canada",
  semrushThirdCountryTraffic: 2000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 1500,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 31000,
  siteUpdateDate: new Date("2024-03-20"),
  domainAuthorityUpdateDate: new Date("2024-03-20"),
  websiteType: "Default",
  language: "English",
  disclaimer: "News coverage only.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 55,
  semrushUpdateDate: new Date("2024-03-20"),
  semrushOrganicTraffic: 31000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-20"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 13,
  pocId: 2,
},
{
  id: 44,
  website: "sigmamusicworld.com",
  niche: "Music",
  contentCategories: "Reviews, News",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 45,
  pageAuthority: 40,
  linkAttribute: "DoFollow",
  ahrefTraffic: 18000,
  spamScore: 3,
  domainRating: 46,
  socialMediaPosting: true,
  sampleURL: "https://sigmamusicworld.com/sample",
  costPrice: 600,
  costPriceValidFrom: new Date("2023-07-20"),
  costPriceValidTo: new Date("2024-07-20"),
  sellingPrice: 750,
  discount: 7,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 120,
  websiteRemark: "Music reviews and news",
  webIP: "198.51.100.200",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(44000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 23000,
  semrushSecondCountryTraffic: 14000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 43000,
  siteUpdateDate: new Date("2024-03-28"),
  domainAuthorityUpdateDate: new Date("2024-03-28"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Music news and reviews.",
  anchorText: true,
  bannerImagePrice: 200,
  costPriceUpdateDate: new Date("2024-01-28"),
  pureCategory: "Entertainment",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 90,
  semrushUpdateDate: new Date("2024-03-28"),
  semrushOrganicTraffic: 43000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-28"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 21,
  pocId: 2,
},
{
  id: 45,
  website: "omegagamingzone.com",
  niche: "Gaming",
  contentCategories: "Reviews, News",
  siteClassification: "Normal",
  priceCategory: "Exchange",
  domainAuthority: 47,
  pageAuthority: 42,
  linkAttribute: "DoFollow",
  ahrefTraffic: 22000,
  spamScore: 4,
  domainRating: 50,
  socialMediaPosting: true,
  sampleURL: "https://omegagamingzone.com/sample",
  costPrice: 650,
  costPriceValidFrom: new Date("2023-08-05"),
  costPriceValidTo: new Date("2024-08-05"),
  sellingPrice: 850,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 140,
  websiteRemark: "Gaming news and reviews",
  webIP: "203.0.113.210",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(56000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 30000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 6000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 2000,
  similarwebTraffic: 54000,
  siteUpdateDate: new Date("2024-04-02"),
  domainAuthorityUpdateDate: new Date("2024-04-02"),
  websiteType: "PR_NonBrand",
  language: "English",
  disclaimer: "Gaming industry news.",
  anchorText: true,
  bannerImagePrice: 240,
  costPriceUpdateDate: new Date("2024-02-15"),
  pureCategory: "Entertainment",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 110,
  semrushUpdateDate: new Date("2024-04-02"),
  semrushOrganicTraffic: 54000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-02"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 22,
  pocId: 2,
},
{
  id: 46,
  website: "alphatraveladventures.com",
  niche: "Travel",
  contentCategories: "Adventure, Tips",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 50,
  pageAuthority: 45,
  linkAttribute: "DoFollow",
  ahrefTraffic: 25000,
  spamScore: 3,
  domainRating: 53,
  socialMediaPosting: true,
  sampleURL: "https://alphatraveladventures.com/sample",
  costPrice: 700,
  costPriceValidFrom: new Date("2023-07-25"),
  costPriceValidTo: new Date("2024-07-25"),
  sellingPrice: 900,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 130,
  websiteRemark: "Travel guides and tips",
  webIP: "198.51.100.220",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(70000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 35000,
  semrushSecondCountryTraffic: 20000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 8000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 4000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 69000,
  siteUpdateDate: new Date("2024-04-05"),
  domainAuthorityUpdateDate: new Date("2024-04-05"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Travel advice.",
  anchorText: true,
  bannerImagePrice: 230,
  costPriceUpdateDate: new Date("2024-02-20"),
  pureCategory: "Travel",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 120,
  semrushUpdateDate: new Date("2024-04-05"),
  semrushOrganicTraffic: 69000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-05"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 28,
  pocId: 2,
},
{
  id: 47,
  website: "betatechreviews.net",
  niche: "Tech Reviews",
  contentCategories: "Software, Hardware",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 54,
  pageAuthority: 50,
  linkAttribute: "DoFollow",
  ahrefTraffic: 27000,
  spamScore: 3,
  domainRating: 56,
  socialMediaPosting: true,
  sampleURL: "https://betatechreviews.net/sample",
  costPrice: 750,
  costPriceValidFrom: new Date("2023-08-10"),
  costPriceValidTo: new Date("2024-08-10"),
  sellingPrice: 900,
  discount: 10,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 140,
  websiteRemark: "Tech reviews and guides",
  webIP: "203.0.113.230",
  webCountry: "USA",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(80000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 42000,
  semrushSecondCountryTraffic: 22000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 8000,
  semrushFourthCountryName: "Germany",
  semrushFourthCountryTraffic: 3000,
  semrushFifthCountryName: "Australia",
  semrushFifthCountryTraffic: 2000,
  similarwebTraffic: 78000,
  siteUpdateDate: new Date("2024-04-01"),
  domainAuthorityUpdateDate: new Date("2024-04-01"),
  websiteType: "PR_Brand",
  language: "English",
  disclaimer: "Trusted tech reviews.",
  anchorText: true,
  bannerImagePrice: 260,
  costPriceUpdateDate: new Date("2024-02-15"),
  pureCategory: "Technology",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 130,
  semrushUpdateDate: new Date("2024-04-01"),
  semrushOrganicTraffic: 78000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-01"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 31,
  pocId: 2,
},
{
  id: 48,
  website: "omegafashionstyle.com",
  niche: "Fashion",
  contentCategories: "Trends, Lifestyle",
  siteClassification: "Normal",
  priceCategory: "Exchange",
  domainAuthority: 44,
  pageAuthority: 40,
  linkAttribute: "DoFollow",
  ahrefTraffic: 16000,
  spamScore: 2,
  domainRating: 43,
  socialMediaPosting: false,
  sampleURL: "https://omegafashionstyle.com/sample",
  costPrice: 530,
  costPriceValidFrom: new Date("2023-09-05"),
  costPriceValidTo: new Date("2024-09-05"),
  sellingPrice: 680,
  discount: 6,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 110,
  websiteRemark: "Fashion and lifestyle tips",
  webIP: "198.51.100.240",
  webCountry: "France",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(38000),
  semrushFirstCountryName: "France",
  semrushSecondCountryName: "Italy",
  semrushFirstCountryTraffic: 21000,
  semrushSecondCountryTraffic: 11000,
  semrushThirdCountryName: "Spain",
  semrushThirdCountryTraffic: 4000,
  semrushFourthCountryName: "UK",
  semrushFourthCountryTraffic: 1500,
  semrushFifthCountryName: "USA",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 37000,
  siteUpdateDate: new Date("2024-04-02"),
  domainAuthorityUpdateDate: new Date("2024-04-02"),
  websiteType: "Default",
  language: "English",
  disclaimer: "Fashion industry updates.",
  anchorText: false,
  bannerImagePrice: 150,
  costPriceUpdateDate: new Date("2024-02-12"),
  pureCategory: "Lifestyle",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 80,
  semrushUpdateDate: new Date("2024-04-02"),
  semrushOrganicTraffic: 37000,
  semrushOrganicTrafficLastUpdated: new Date("2024-04-02"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 35,
  pocId: 2,
},
{
  id: 49,
  website: "zetasportsonline.com",
  niche: "Sports",
  contentCategories: "Football, Basketball",
  siteClassification: "Normal",
  priceCategory: "Paid",
  domainAuthority: 46,
  pageAuthority: 42,
  linkAttribute: "DoFollow",
  ahrefTraffic: 21000,
  spamScore: 3,
  domainRating: 48,
  socialMediaPosting: true,
  sampleURL: "https://zetasportsonline.com/sample",
  costPrice: 620,
  costPriceValidFrom: new Date("2023-07-01"),
  costPriceValidTo: new Date("2024-07-01"),
  sellingPrice: 800,
  discount: 8,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 120,
  websiteRemark: "Sports news and analysis",
  webIP: "203.0.113.250",
  webCountry: "UK",
  turnAroundTime: "24h",
  semrushTraffic: BigInt(54000),
  semrushFirstCountryName: "UK",
  semrushSecondCountryName: "USA",
  semrushFirstCountryTraffic: 30000,
  semrushSecondCountryTraffic: 15000,
  semrushThirdCountryName: "Canada",
  semrushThirdCountryTraffic: 5000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2500,
  semrushFifthCountryName: "Germany",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 53000,
  siteUpdateDate: new Date("2024-03-20"),
  domainAuthorityUpdateDate: new Date("2024-03-20"),
  websiteType: "PR",
  language: "English",
  disclaimer: "Sports coverage and news.",
  anchorText: true,
  bannerImagePrice: 210,
  costPriceUpdateDate: new Date("2024-01-25"),
  pureCategory: "Sports",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "Pure",
  numberOfLinks: 100,
  semrushUpdateDate: new Date("2024-03-20"),
  semrushOrganicTraffic: 53000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-20"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 24,
  pocId: 2,
},
{
  id: 50,
  website: "alphapodcastmedia.com",
  niche: "Media",
  contentCategories: "Podcasts, Streaming",
  siteClassification: "Normal",
  priceCategory: "Free",
  domainAuthority: 40,
  pageAuthority: 35,
  linkAttribute: "NoFollow",
  ahrefTraffic: 15000,
  spamScore: 2,
  domainRating: 42,
  socialMediaPosting: false,
  sampleURL: "https://alphapodcastmedia.com/sample",
  costPrice: 0,
  costPriceValidFrom: null,
  costPriceValidTo: null,
  sellingPrice: null,
  discount: null,
  adultPrice: 0,
  casinoAdultPrice: 0,
  cbdPrice: 0,
  linkInsertionCost: 0,
  websiteRemark: "Podcast streaming platform",
  webIP: "198.51.100.250",
  webCountry: "USA",
  turnAroundTime: "48h",
  semrushTraffic: BigInt(35000),
  semrushFirstCountryName: "USA",
  semrushSecondCountryName: "Canada",
  semrushFirstCountryTraffic: 18000,
  semrushSecondCountryTraffic: 12000,
  semrushThirdCountryName: "UK",
  semrushThirdCountryTraffic: 3000,
  semrushFourthCountryName: "Australia",
  semrushFourthCountryTraffic: 2000,
  semrushFifthCountryName: "New Zealand",
  semrushFifthCountryTraffic: 1000,
  similarwebTraffic: 34000,
  siteUpdateDate: new Date("2024-03-18"),
  domainAuthorityUpdateDate: new Date("2024-03-18"),
  websiteType: "Language",
  language: "English",
  disclaimer: "Podcasts and streaming.",
  anchorText: false,
  bannerImagePrice: 0,
  costPriceUpdateDate: null,
  pureCategory: "Media",
  availability: true,
  isIndexed: true,
  websiteStatus: "Normal",
  websiteQuality: "AlmostPure",
  numberOfLinks: 65,
  semrushUpdateDate: new Date("2024-03-18"),
  semrushOrganicTraffic: 34000,
  semrushOrganicTrafficLastUpdated: new Date("2024-03-18"),
  createdAt: new Date(),
  updatedAt: new Date(),
  vendorId: 16,
  pocId: 2,
},
]

const prisma = new PrismaClient();

async function main() {
    for (const website of siteSeed) {
        await prisma.site.create({
            data: website,
        });
    }
    console.log("Websites seeded successfully.");
}   

main();

