import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const seedOrder = [
  {
    id: 1,
    orderNumber: 10001,
    orderDate: new Date("2024-01-10"),
    orderCostPrice: 1200,
    orderStatus: "Pending",
    vendorAssignedDate: new Date("2024-01-11"),
    orderStatusUpdateDate: new Date("2024-01-12"),
    publishDate: null,
    publishURL: null,
    orderRemark: "Urgent delivery",
    mainRemark: "Priority client",
    clientPaymentRemark: null,
    clientContentCost: 1500,
    clientProposedAmount: 1700,
    clientPaymentStatus: "Pending",
    clientReceivedAmount: null,
    clientPaymentDate: null,
    vendorInvoiceStatus: "Pending",
    vendorPaymentStatus: "Unpaid",
    vendorPaymentDate: null,
    vendorPaymentAmount: null,
    invoiceNumber: null,
    costPriceWithGST: 1400,
    indexedScreenShotLink: null,
    siteId: 27,
    salesPersonId: 2,
    clientId: 13,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    orderNumber: 10002,
    orderDate: new Date("2024-01-15"),
    orderCostPrice: 900,
    orderStatus: "Given",
    vendorAssignedDate: new Date("2024-01-16"),
    orderStatusUpdateDate: new Date("2024-01-17"),
    publishDate: new Date("2024-02-01"),
    publishURL: "https://example.com/published/10002",
    orderRemark: "Includes bonus content",
    mainRemark: null,
    clientPaymentRemark: "Partial payment done",
    clientContentCost: 1100,
    clientProposedAmount: 1300,
    clientPaymentStatus: "PartiallyReceived",
    clientReceivedAmount: 700,
    clientPaymentDate: new Date("2024-01-20"),
    vendorInvoiceStatus: "Ask",
    vendorPaymentStatus: "Unpaid",
    vendorPaymentDate: null,
    vendorPaymentAmount: null,
    invoiceNumber: "INV1002",
    costPriceWithGST: 1050,
    indexedScreenShotLink: "https://screenshots.com/10002.png",
    siteId: 8,
    salesPersonId: 2,
    clientId: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    orderNumber: 10003,
    orderDate: new Date("2024-02-05"),
    orderCostPrice: 1500,
    orderStatus: "Publish",
    vendorAssignedDate: new Date("2024-02-06"),
    orderStatusUpdateDate: new Date("2024-02-10"),
    publishDate: new Date("2024-02-15"),
    publishURL: "https://example.com/published/10003",
    orderRemark: null,
    mainRemark: "Client satisfied",
    clientPaymentRemark: "Paid in full",
    clientContentCost: 1700,
    clientProposedAmount: 1800,
    clientPaymentStatus: "Received",
    clientReceivedAmount: 1800,
    clientPaymentDate: new Date("2024-02-14"),
    vendorInvoiceStatus: "Paid",
    vendorPaymentStatus: "Paid",
    vendorPaymentDate: new Date("2024-02-20"),
    vendorPaymentAmount: 1600,
    invoiceNumber: "INV1003",
    costPriceWithGST: 1600,
    indexedScreenShotLink: null,
    siteId: 14,
    salesPersonId: 2,
    clientId: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    orderNumber: 10004,
    orderDate: new Date("2024-02-12"),
    orderCostPrice: 800,
    orderStatus: "NotPublish",
    vendorAssignedDate: null,
    orderStatusUpdateDate: null,
    publishDate: null,
    publishURL: null,
    orderRemark: "Follow up needed",
    mainRemark: null,
    clientPaymentRemark: null,
    clientContentCost: 950,
    clientProposedAmount: 1100,
    clientPaymentStatus: "Pending",
    clientReceivedAmount: null,
    clientPaymentDate: null,
    vendorInvoiceStatus: "Pending",
    vendorPaymentStatus: "Unpaid",
    vendorPaymentDate: null,
    vendorPaymentAmount: null,
    invoiceNumber: null,
    costPriceWithGST: 880,
    indexedScreenShotLink: null,
    siteId: 33,
    salesPersonId: 2,
    clientId: 36,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    orderNumber: 10005,
    orderDate: new Date("2024-03-01"),
    orderCostPrice: 1300,
    orderStatus: "Cancel",
    vendorAssignedDate: new Date("2024-03-02"),
    orderStatusUpdateDate: new Date("2024-03-05"),
    publishDate: null,
    publishURL: null,
    orderRemark: null,
    mainRemark: "Urgent task",
    clientPaymentRemark: "Awaiting payment",
    clientContentCost: 1500,
    clientProposedAmount: 1650,
    clientPaymentStatus: "Pending",
    clientReceivedAmount: null,
    clientPaymentDate: null,
    vendorInvoiceStatus: "Pending",
    vendorPaymentStatus: "Unpaid",
    vendorPaymentDate: null,
    vendorPaymentAmount: null,
    invoiceNumber: "INV1005",
    costPriceWithGST: 1430,
    indexedScreenShotLink: null,
    siteId: 40,
    salesPersonId: 2,
    clientId: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    orderNumber: 10006,
    orderDate: new Date("2024-03-10"),
    orderCostPrice: 1100,
    orderStatus: "Replacement",
    vendorAssignedDate: new Date("2024-03-11"),
    orderStatusUpdateDate: new Date("2024-03-15"),
    publishDate: new Date("2024-03-20"),
    publishURL: "https://example.com/published/10006",
    orderRemark: "Repeat client",
    mainRemark: null,
    clientPaymentRemark: "Paid fully",
    clientContentCost: 1250,
    clientProposedAmount: 1350,
    clientPaymentStatus: "Received",
    clientReceivedAmount: 1350,
    clientPaymentDate: new Date("2024-03-18"),
    vendorInvoiceStatus: "Paid",
    vendorPaymentStatus: "Paid",
    vendorPaymentDate: new Date("2024-03-22"),
    vendorPaymentAmount: 1200,
    invoiceNumber: "INV1006",
    costPriceWithGST: 1200,
    indexedScreenShotLink: null,
    siteId: 22,
    salesPersonId: 2,
    clientId: 25,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    orderNumber: 10007,
    orderDate: new Date("2024-03-15"),
    orderCostPrice: 950,
    orderStatus: "NeedUpdate",
    vendorAssignedDate: null,
    orderStatusUpdateDate: null,
    publishDate: null,
    publishURL: null,
    orderRemark: "Client requested demo",
    mainRemark: null,
    clientPaymentRemark: null,
    clientContentCost: 1100,
    clientProposedAmount: 1200,
    clientPaymentStatus: "Pending",
    clientReceivedAmount: null,
    clientPaymentDate: null,
    vendorInvoiceStatus: "Pending",
    vendorPaymentStatus: "Unpaid",
    vendorPaymentDate: null,
    vendorPaymentAmount: null,
    invoiceNumber: null,
    costPriceWithGST: 1025,
    indexedScreenShotLink: null,
    siteId: 15,
    salesPersonId: 2,
    clientId: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    orderNumber: 10008,
    orderDate: new Date("2024-03-20"),
    orderCostPrice: 1250,
    orderStatus: "Order_Replaced",
    vendorAssignedDate: new Date("2024-03-21"),
    orderStatusUpdateDate: new Date("2024-03-22"),
    publishDate: null,
    publishURL: null,
    orderRemark: "Include extended support",
    mainRemark: "Needs customization",
    clientPaymentRemark: "Deposit received",
    clientContentCost: 1400,
    clientProposedAmount: 1550,
    clientPaymentStatus: "PartiallyReceived",
    clientReceivedAmount: 700,
    clientPaymentDate: new Date("2024-03-23"),
    vendorInvoiceStatus: "Pending",
    vendorPaymentStatus: "Unpaid",
    vendorPaymentDate: null,
    vendorPaymentAmount: null,
    invoiceNumber: "INV1008",
    costPriceWithGST: 1350,
    indexedScreenShotLink: "https://screenshots.com/10008.png",
    siteId: 35,
    salesPersonId: 2,
    clientId: 17,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
  id: 9,
  orderNumber: 10009,
  orderDate: new Date("2024-04-01"),
  orderCostPrice: 1000,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-04-02"),
  orderStatusUpdateDate: new Date("2024-04-05"),
  publishDate: new Date("2024-04-10"),
  publishURL: "https://example.com/published/10009",
  orderRemark: null,
  mainRemark: "Excellent feedback",
  clientPaymentRemark: "Paid on time",
  clientContentCost: 1150,
  clientProposedAmount: 1300,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1300,
  clientPaymentDate: new Date("2024-04-08"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-04-12"),
  vendorPaymentAmount: 1100,
  invoiceNumber: "INV1009",
  costPriceWithGST: 1100,
  indexedScreenShotLink: null,
  siteId: 44,
  salesPersonId: 2,
  clientId: 29,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 10,
  orderNumber: 10010,
  orderDate: new Date("2024-04-10"),
  orderCostPrice: 1150,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-04-11"),
  orderStatusUpdateDate: new Date("2024-04-13"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Awaiting client approval",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1300,
  clientProposedAmount: 1450,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1010",
  costPriceWithGST: 1250,
  indexedScreenShotLink: null,
  siteId: 20,
  salesPersonId: 2,
  clientId: 22,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 11,
  orderNumber: 10011,
  orderDate: new Date("2024-04-15"),
  orderCostPrice: 1350,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Check for compatibility",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1420,
  indexedScreenShotLink: null,
  siteId: 42,
  salesPersonId: 2,
  clientId: 34,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 12,
  orderNumber: 10012,
  orderDate: new Date("2024-04-20"),
  orderCostPrice: 1250,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-04-21"),
  orderStatusUpdateDate: new Date("2024-04-25"),
  publishDate: new Date("2024-04-30"),
  publishURL: "https://example.com/published/10012",
  orderRemark: null,
  mainRemark: "Delivered successfully",
  clientPaymentRemark: "Payment received",
  clientContentCost: 1400,
  clientProposedAmount: 1550,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1550,
  clientPaymentDate: new Date("2024-04-29"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-05-02"),
  vendorPaymentAmount: 1350,
  invoiceNumber: "INV1012",
  costPriceWithGST: 1350,
  indexedScreenShotLink: "https://screenshots.com/10012.png",
  siteId: 7,
  salesPersonId: 2,
  clientId: 11,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 13,
  orderNumber: 10013,
  orderDate: new Date("2024-04-25"),
  orderCostPrice: 1100,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-04-26"),
  orderStatusUpdateDate: new Date("2024-04-28"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Include extra feature",
  mainRemark: "Client requested add-on",
  clientPaymentRemark: "Partial payment received",
  clientContentCost: 1300,
  clientProposedAmount: 1450,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 750,
  clientPaymentDate: new Date("2024-04-27"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1013",
  costPriceWithGST: 1250,
  indexedScreenShotLink: null,
  siteId: 31,
  salesPersonId: 2,
  clientId: 5,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 14,
  orderNumber: 10014,
  orderDate: new Date("2024-05-01"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Waiting on client feedback",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 12,
  salesPersonId: 2,
  clientId: 39,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 15,
  orderNumber: 10015,
  orderDate: new Date("2024-05-05"),
  orderCostPrice: 1300,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-05-06"),
  orderStatusUpdateDate: new Date("2024-05-08"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Design phase ongoing",
  mainRemark: null,
  clientPaymentRemark: "Partial deposit",
  clientContentCost: 1500,
  clientProposedAmount: 1600,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 800,
  clientPaymentDate: new Date("2024-05-07"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1015",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 18,
  salesPersonId: 2,
  clientId: 23,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 16,
  orderNumber: 10016,
  orderDate: new Date("2024-05-10"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client delayed payment",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 5,
  salesPersonId: 2,
  clientId: 12,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 17,
  orderNumber: 10017,
  orderDate: new Date("2024-05-15"),
  orderCostPrice: 1300,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-05-16"),
  orderStatusUpdateDate: new Date("2024-05-18"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Adding SEO services",
  mainRemark: "Client upsold",
  clientPaymentRemark: "Advance received",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 700,
  clientPaymentDate: new Date("2024-05-17"),
  vendorInvoiceStatus: "Ask",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1017",
  costPriceWithGST: 1400,
  indexedScreenShotLink: "https://screenshots.com/10017.png",
  siteId: 41,
  salesPersonId: 2,
  clientId: 44,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 18,
  orderNumber: 10018,
  orderDate: new Date("2024-05-20"),
  orderCostPrice: 900,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-05-21"),
  orderStatusUpdateDate: new Date("2024-05-23"),
  publishDate: new Date("2024-05-28"),
  publishURL: "https://example.com/published/10018",
  orderRemark: null,
  mainRemark: "Delivered ahead of schedule",
  clientPaymentRemark: "Full payment received",
  clientContentCost: 1100,
  clientProposedAmount: 1250,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1250,
  clientPaymentDate: new Date("2024-05-27"),
  vendorInvoiceStatus: "Received",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-05-30"),
  vendorPaymentAmount: 1050,
  invoiceNumber: "INV1018",
  costPriceWithGST: 1050,
  indexedScreenShotLink: null,
  siteId: 24,
  salesPersonId: 2,
  clientId: 6,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 19,
  orderNumber: 10019,
  orderDate: new Date("2024-05-25"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client requested changes",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1450,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1250,
  indexedScreenShotLink: null,
  siteId: 17,
  salesPersonId: 2,
  clientId: 38,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 20,
  orderNumber: 10020,
  orderDate: new Date("2024-06-01"),
  orderCostPrice: 1400,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-06-02"),
  orderStatusUpdateDate: new Date("2024-06-05"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Adding extended warranty",
  mainRemark: "Upsell approved",
  clientPaymentRemark: "Partial payment",
  clientContentCost: 1600,
  clientProposedAmount: 1800,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 900,
  clientPaymentDate: new Date("2024-06-03"),
  vendorInvoiceStatus: "Ask",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1020",
  costPriceWithGST: 1500,
  indexedScreenShotLink: "https://screenshots.com/10020.png",
  siteId: 12,
  salesPersonId: 2,
  clientId: 30,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 21,
  orderNumber: 10021,
  orderDate: new Date("2024-06-05"),
  orderCostPrice: 1000,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-06-06"),
  orderStatusUpdateDate: new Date("2024-06-08"),
  publishDate: new Date("2024-06-12"),
  publishURL: "https://example.com/published/10021",
  orderRemark: null,
  mainRemark: "Highly satisfied client",
  clientPaymentRemark: "Paid fully",
  clientContentCost: 1150,
  clientProposedAmount: 1300,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1300,
  clientPaymentDate: new Date("2024-06-10"),
  vendorInvoiceStatus: "Received",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-06-15"),
  vendorPaymentAmount: 1100,
  invoiceNumber: "INV1021",
  costPriceWithGST: 1100,
  indexedScreenShotLink: null,
  siteId: 38,
  salesPersonId: 2,
  clientId: 2,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 22,
  orderNumber: 10022,
  orderDate: new Date("2024-06-10"),
  orderCostPrice: 1200,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-06-11"),
  orderStatusUpdateDate: new Date("2024-06-14"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Awaiting client confirmation",
  mainRemark: null,
  clientPaymentRemark: "Partial advance",
  clientContentCost: 1400,
  clientProposedAmount: 1550,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 700,
  clientPaymentDate: new Date("2024-06-12"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1022",
  costPriceWithGST: 1350,
  indexedScreenShotLink: null,
  siteId: 23,
  salesPersonId: 2,
  clientId: 48,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 23,
  orderNumber: 10023,
  orderDate: new Date("2024-06-15"),
  orderCostPrice: 1300,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client requested quote revision",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 19,
  salesPersonId: 2,
  clientId: 16,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 24,
  orderNumber: 10024,
  orderDate: new Date("2024-06-20"),
  orderCostPrice: 1100,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-06-21"),
  orderStatusUpdateDate: new Date("2024-06-23"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Additional testing required",
  mainRemark: null,
  clientPaymentRemark: "Deposit received",
  clientContentCost: 1300,
  clientProposedAmount: 1450,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 650,
  clientPaymentDate: new Date("2024-06-22"),
  vendorInvoiceStatus: "Ask",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1024",
  costPriceWithGST: 1250,
  indexedScreenShotLink: "https://screenshots.com/10024.png",
  siteId: 1,
  salesPersonId: 2,
  clientId: 20,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 25,
  orderNumber: 10025,
  orderDate: new Date("2024-06-25"),
  orderCostPrice: 1250,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-06-26"),
  orderStatusUpdateDate: new Date("2024-06-29"),
  publishDate: new Date("2024-07-03"),
  publishURL: "https://example.com/published/10025",
  orderRemark: null,
  mainRemark: "Excellent client cooperation",
  clientPaymentRemark: "Paid full amount",
  clientContentCost: 1450,
  clientProposedAmount: 1600,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1600,
  clientPaymentDate: new Date("2024-07-01"),
  vendorInvoiceStatus: "Received",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-07-05"),
  vendorPaymentAmount: 1350,
  invoiceNumber: "INV1025",
  costPriceWithGST: 1350,
  indexedScreenShotLink: null,
  siteId: 9,
  salesPersonId: 2,
  clientId: 3,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 26,
  orderNumber: 10026,
  orderDate: new Date("2024-07-01"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client requested delay",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1450,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 6,
  salesPersonId: 2,
  clientId: 15,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 27,
  orderNumber: 10027,
  orderDate: new Date("2024-07-05"),
  orderCostPrice: 1300,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-07-06"),
  orderStatusUpdateDate: new Date("2024-07-08"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Additional resources needed",
  mainRemark: "Scope changed",
  clientPaymentRemark: "Partial payment done",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 800,
  clientPaymentDate: new Date("2024-07-07"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1027",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 13,
  salesPersonId: 2,
  clientId: 8,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 28,
  orderNumber: 10028,
  orderDate: new Date("2024-07-10"),
  orderCostPrice: 900,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-07-11"),
  orderStatusUpdateDate: new Date("2024-07-13"),
  publishDate: new Date("2024-07-18"),
  publishURL: "https://example.com/published/10028",
  orderRemark: null,
  mainRemark: "Delivered ahead of time",
  clientPaymentRemark: "Payment cleared",
  clientContentCost: 1100,
  clientProposedAmount: 1250,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1250,
  clientPaymentDate: new Date("2024-07-17"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-07-20"),
  vendorPaymentAmount: 1050,
  invoiceNumber: "INV1028",
  costPriceWithGST: 1050,
  indexedScreenShotLink: null,
  siteId: 21,
  salesPersonId: 2,
  clientId: 47,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 29,
  orderNumber: 10029,
  orderDate: new Date("2024-07-15"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client requested revision",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 28,
  salesPersonId: 2,
  clientId: 18,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 30,
  orderNumber: 10030,
  orderDate: new Date("2024-07-20"),
  orderCostPrice: 1300,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-07-21"),
  orderStatusUpdateDate: new Date("2024-07-23"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Awaiting client feedback",
  mainRemark: null,
  clientPaymentRemark: "Partial advance",
  clientContentCost: 1500,
  clientProposedAmount: 1600,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 800,
  clientPaymentDate: new Date("2024-07-22"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1030",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 30,
  salesPersonId: 2,
  clientId: 9,
  createdAt: new Date(),
  updatedAt: new Date(),
}, 
{
  id: 31,
  orderNumber: 10031,
  orderDate: new Date("2024-07-25"),
  orderCostPrice: 1250,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-07-26"),
  orderStatusUpdateDate: new Date("2024-07-29"),
  publishDate: new Date("2024-08-03"),
  publishURL: "https://example.com/published/10031",
  orderRemark: null,
  mainRemark: "Delivered on time",
  clientPaymentRemark: "Full payment received",
  clientContentCost: 1400,
  clientProposedAmount: 1550,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1550,
  clientPaymentDate: new Date("2024-08-02"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-08-05"),
  vendorPaymentAmount: 1350,
  invoiceNumber: "INV1031",
  costPriceWithGST: 1350,
  indexedScreenShotLink: null,
  siteId: 11,
  salesPersonId: 2,
  clientId: 14,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 32,
  orderNumber: 10032,
  orderDate: new Date("2024-08-01"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client needs update",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 9,
  salesPersonId: 2,
  clientId: 27,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 33,
  orderNumber: 10033,
  orderDate: new Date("2024-08-05"),
  orderCostPrice: 1300,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-08-06"),
  orderStatusUpdateDate: new Date("2024-08-08"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Requested additional features",
  mainRemark: "Scope increased",
  clientPaymentRemark: "Partial payment done",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 800,
  clientPaymentDate: new Date("2024-08-07"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1033",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 7,
  salesPersonId: 2,
  clientId: 26,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 34,
  orderNumber: 10034,
  orderDate: new Date("2024-08-10"),
  orderCostPrice: 900,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-08-11"),
  orderStatusUpdateDate: new Date("2024-08-13"),
  publishDate: new Date("2024-08-18"),
  publishURL: "https://example.com/published/10034",
  orderRemark: null,
  mainRemark: "Client very happy",
  clientPaymentRemark: "Payment received",
  clientContentCost: 1100,
  clientProposedAmount: 1250,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1250,
  clientPaymentDate: new Date("2024-08-17"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-08-20"),
  vendorPaymentAmount: 1050,
  invoiceNumber: "INV1034",
  costPriceWithGST: 1050,
  indexedScreenShotLink: null,
  siteId: 18,
  salesPersonId: 2,
  clientId: 31,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 35,
  orderNumber: 10035,
  orderDate: new Date("2024-08-15"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client on vacation",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 3,
  salesPersonId: 2,
  clientId: 43,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 36,
  orderNumber: 10036,
  orderDate: new Date("2024-08-20"),
  orderCostPrice: 1300,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-08-21"),
  orderStatusUpdateDate: new Date("2024-08-23"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Design revisions requested",
  mainRemark: null,
  clientPaymentRemark: "Partial payment",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 900,
  clientPaymentDate: new Date("2024-08-22"),
  vendorInvoiceStatus: "Ask",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1036",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 26,
  salesPersonId: 2,
  clientId: 4,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 37,
  orderNumber: 10037,
  orderDate: new Date("2024-08-25"),
  orderCostPrice: 1000,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-08-26"),
  orderStatusUpdateDate: new Date("2024-08-28"),
  publishDate: new Date("2024-09-01"),
  publishURL: "https://example.com/published/10037",
  orderRemark: null,
  mainRemark: "Client pleased with delivery",
  clientPaymentRemark: "Paid in full",
  clientContentCost: 1150,
  clientProposedAmount: 1300,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1300,
  clientPaymentDate: new Date("2024-08-31"),
  vendorInvoiceStatus: "Received",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-09-05"),
  vendorPaymentAmount: 1100,
  invoiceNumber: "INV1037",
  costPriceWithGST: 1100,
  indexedScreenShotLink: null,
  siteId: 37,
  salesPersonId: 2,
  clientId: 28,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 38,
  orderNumber: 10038,
  orderDate: new Date("2024-09-01"),
  orderCostPrice: 1200,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client requested postponement",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1250,
  indexedScreenShotLink: null,
  siteId: 10,
  salesPersonId: 2,
  clientId: 37,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 39,
  orderNumber: 10039,
  orderDate: new Date("2024-09-05"),
  orderCostPrice: 1350,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-09-06"),
  orderStatusUpdateDate: new Date("2024-09-08"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Additional documentation requested",
  mainRemark: null,
  clientPaymentRemark: "Partial payment received",
  clientContentCost: 1550,
  clientProposedAmount: 1700,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 800,
  clientPaymentDate: new Date("2024-09-07"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1039",
  costPriceWithGST: 1450,
  indexedScreenShotLink: null,
  siteId: 34,
  salesPersonId: 2,
  clientId: 32,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 40,
  orderNumber: 10040,
  orderDate: new Date("2024-09-10"),
  orderCostPrice: 900,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-09-11"),
  orderStatusUpdateDate: new Date("2024-09-13"),
  publishDate: new Date("2024-09-18"),
  publishURL: "https://example.com/published/10040",
  orderRemark: null,
  mainRemark: "Client very satisfied",
  clientPaymentRemark: "Payment received",
  clientContentCost: 1100,
  clientProposedAmount: 1250,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1250,
  clientPaymentDate: new Date("2024-09-17"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-09-20"),
  vendorPaymentAmount: 1050,
  invoiceNumber: "INV1040",
  costPriceWithGST: 1050,
  indexedScreenShotLink: null,
  siteId: 25,
  salesPersonId: 2,
  clientId: 1,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 41,
  orderNumber: 10041,
  orderDate: new Date("2024-09-15"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client considering options",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 16,
  salesPersonId: 2,
  clientId: 19,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 42,
  orderNumber: 10042,
  orderDate: new Date("2024-09-20"),
  orderCostPrice: 1300,
  orderStatus: "Order_Replaced",
  vendorAssignedDate: new Date("2024-09-21"),
  orderStatusUpdateDate: new Date("2024-09-23"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Additional testing required",
  mainRemark: null,
  clientPaymentRemark: "Partial advance received",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 900,
  clientPaymentDate: new Date("2024-09-22"),
  vendorInvoiceStatus: "Ask",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1042",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 29,
  salesPersonId: 2,
  clientId: 41,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 43,
  orderNumber: 10043,
  orderDate: new Date("2024-09-25"),
  orderCostPrice: 1000,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-09-26"),
  orderStatusUpdateDate: new Date("2024-09-28"),
  publishDate: new Date("2024-10-02"),
  publishURL: "https://example.com/published/10043",
  orderRemark: null,
  mainRemark: "Client pleased with service",
  clientPaymentRemark: "Paid full amount",
  clientContentCost: 1150,
  clientProposedAmount: 1300,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1300,
  clientPaymentDate: new Date("2024-10-01"),
  vendorInvoiceStatus: "Received",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-10-05"),
  vendorPaymentAmount: 1100,
  invoiceNumber: "INV1043",
  costPriceWithGST: 1100,
  indexedScreenShotLink: null,
  siteId: 4,
  salesPersonId: 2,
  clientId: 33,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 44,
  orderNumber: 10044,
  orderDate: new Date("2024-10-01"),
  orderCostPrice: 1200,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client delayed response",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1250,
  indexedScreenShotLink: null,
  siteId: 34,
  salesPersonId: 2,
  clientId: 24,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 45,
  orderNumber: 10045,
  orderDate: new Date("2024-10-05"),
  orderCostPrice: 1300,
  orderStatus: "Replacement",
  vendorAssignedDate: new Date("2024-10-06"),
  orderStatusUpdateDate: new Date("2024-10-08"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Scope creep identified",
  mainRemark: null,
  clientPaymentRemark: "Partial payment",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 800,
  clientPaymentDate: new Date("2024-10-07"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1045",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 27,
  salesPersonId: 2,
  clientId: 35,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 46,
  orderNumber: 10046,
  orderDate: new Date("2024-10-10"),
  orderCostPrice: 900,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-10-11"),
  orderStatusUpdateDate: new Date("2024-10-13"),
  publishDate: new Date("2024-10-18"),
  publishURL: "https://example.com/published/10046",
  orderRemark: null,
  mainRemark: "Great client satisfaction",
  clientPaymentRemark: "Paid full",
  clientContentCost: 1100,
  clientProposedAmount: 1250,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1250,
  clientPaymentDate: new Date("2024-10-17"),
  vendorInvoiceStatus: "Paid",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-10-20"),
  vendorPaymentAmount: 1050,
  invoiceNumber: "INV1046",
  costPriceWithGST: 1050,
  indexedScreenShotLink: null,
  siteId: 1,
  salesPersonId: 2,
  clientId: 22,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 47,
  orderNumber: 10047,
  orderDate: new Date("2024-10-15"),
  orderCostPrice: 1150,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Awaiting client approval",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1230,
  indexedScreenShotLink: null,
  siteId: 16,
  salesPersonId: 2,
  clientId: 9,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 48,
  orderNumber: 10048,
  orderDate: new Date("2024-10-20"),
  orderCostPrice: 1300,
  orderStatus: "Given",
  vendorAssignedDate: new Date("2024-10-21"),
  orderStatusUpdateDate: new Date("2024-10-23"),
  publishDate: null,
  publishURL: null,
  orderRemark: "Client requested additional feature",
  mainRemark: null,
  clientPaymentRemark: "Partial advance",
  clientContentCost: 1500,
  clientProposedAmount: 1650,
  clientPaymentStatus: "PartiallyReceived",
  clientReceivedAmount: 900,
  clientPaymentDate: new Date("2024-10-22"),
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: "INV1048",
  costPriceWithGST: 1400,
  indexedScreenShotLink: null,
  siteId: 11,
  salesPersonId: 2,
  clientId: 7,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 49,
  orderNumber: 10049,
  orderDate: new Date("2024-10-25"),
  orderCostPrice: 1000,
  orderStatus: "Publish",
  vendorAssignedDate: new Date("2024-10-26"),
  orderStatusUpdateDate: new Date("2024-10-28"),
  publishDate: new Date("2024-11-01"),
  publishURL: "https://example.com/published/10049",
  orderRemark: null,
  mainRemark: "Excellent delivery",
  clientPaymentRemark: "Paid fully",
  clientContentCost: 1150,
  clientProposedAmount: 1300,
  clientPaymentStatus: "Received",
  clientReceivedAmount: 1300,
  clientPaymentDate: new Date("2024-10-31"),
  vendorInvoiceStatus: "Received",
  vendorPaymentStatus: "Paid",
  vendorPaymentDate: new Date("2024-11-05"),
  vendorPaymentAmount: 1100,
  invoiceNumber: "INV1049",
  costPriceWithGST: 1100,
  indexedScreenShotLink: null,
  siteId: 14,
  salesPersonId: 2,
  clientId: 39,
  createdAt: new Date(),
  updatedAt: new Date(),
},
{
  id: 50,
  orderNumber: 10050,
  orderDate: new Date("2024-11-01"),
  orderCostPrice: 1200,
  orderStatus: "Pending",
  vendorAssignedDate: null,
  orderStatusUpdateDate: null,
  publishDate: null,
  publishURL: null,
  orderRemark: "Client considering contract renewal",
  mainRemark: null,
  clientPaymentRemark: null,
  clientContentCost: 1350,
  clientProposedAmount: 1500,
  clientPaymentStatus: "Pending",
  clientReceivedAmount: null,
  clientPaymentDate: null,
  vendorInvoiceStatus: "Pending",
  vendorPaymentStatus: "Unpaid",
  vendorPaymentDate: null,
  vendorPaymentAmount: null,
  invoiceNumber: null,
  costPriceWithGST: 1250,
  indexedScreenShotLink: null,
  siteId: 19,
  salesPersonId: 2,
  clientId: 21,
  createdAt: new Date(),
  updatedAt: new Date(),
}

]

async function main() {
    for (const order of seedOrder) {
        await prisma.order.create({
        data: order,
        });
    }
    console.log("Orders seeded successfully");
    }

main();
